### ISSUE TITLE
Customize Snipplet

### ISSUE THREAD

**Issue by nexflo** [ethercreative/seo#1]
First of: Awesome plugin mate!

Is there an option (or how) does one define "standart" text for the snipplets? Title, description etc?

**Comment by Tam** [comment]
Hi, glad you like it!

You can define the default title suffix on a global (plugin settings) and per-field (field settings) basis, but you can't set default text for the description in the plugin. We may add this functionality as we expand the snippet, but our aim is to keep the plugin as non-restrictive as possible for the person writing the copy, and as an attempt to get users to write unique meta descriptions.

If you wanted a fall back for an empty description, you could do something like:

```twig
{# Where `entry.seo` is the field & `seo` is the variable required in the <head> #}
{% set seo = craft.seo.custom(entry.seo.title, entry.seo.description ?: 'My default description', false) %}
```

or globally:

```twig
<meta name="description" content="{{ seo.description ?: 'My default global description' }}" />
```

But it's worth keeping in mind that, [according to Google](https://www.youtube.com/watch?v=W4gr88oHb-k), it's better to have unique meta descriptions or no meta description at all than having duplicate descriptions.

Hope this helps!
