### ISSUE TITLE
No robot.txt generated. 404 thrown.

### ISSUE THREAD

**Issue by RyanHavoc** [ethercreative/seo#100]
### Description
First time using the SEO plugin.

After installing the plugin mydomain.com/sitemap.xml works fine but mydomain.com/robots.txt returns a 404 page. Should this just work "out of the box"?

### Steps to reproduce

1. Install plugin
2. Visit /robots.txt

### Additional info

- Craft version: 3.0.8
- SEO version: 3.2.8
- PHP version: 7.1
- Database driver & version: MySQL
- Other Plugins:

**Comment by alexjcollins** [comment]
@RyanHavoc You should be able to just head to /robots.txt - it's programatically generated.

Are you definitely on the latest version of the plugin? If you're logged in as an admin, can you access it (as 3.2.8 fixed a bug that only made it available if you were logged in). What's your site baseUrl set to?

**Comment by RyanHavoc** [comment]
@alexjcollins That's what I thought. I've literally just installed it from the Plugin Store about 3 hours ago so I'm on 3.2.8.

Base URL is set to @web but I've just tried it as an actual url but I just get a 404 for /robots.txt...

**Comment by Tam** [comment]
Is this still an issue? I've just installed the plugin on a fresh Craft install and everything worked fine. Can you confirm that the plugin is installed and you don't have any templates or routes that could be overriding `/robots.txt`?

**Comment by RyanHavoc** [comment]
It was for me. Sorry, can't help further as went with a different plugin.
