### ISSUE TITLE
Lightswitches don't render properly

### ISSUE THREAD

**Issue by lukeyouell** [ethercreative/seo#103]
Latest version of Chrome (Mac):
![image](https://user-images.githubusercontent.com/24975058/40968653-fa79dfd8-68ad-11e8-9f3a-d829af094d11.png)

Latest version of Firefox Quantum (Mac) - notice the edges:
![image](https://user-images.githubusercontent.com/24975058/40968764-3dba2078-68ae-11e8-80ac-2b19373873cf.png)

**Comment by Tam** [comment]
We use Crafts built-in lightswitches, so this is more of a Craft related issue. I've just tested in Firefox & Chrome and don't see any graphical issues, so I'll consider this fixed.

**Comment by lukeyouell** [comment]
@Tam unfortunately this isn't fixed, the issue can be replicated across multiple devices and browsers.

The issue looks to be caused by the `seo--switch` class being applied to the wrapping div.

With `seo--switch` wrapper:
![image](https://user-images.githubusercontent.com/24975058/41857282-08eeef2c-788f-11e8-9547-a49a245982fd.png)

Without:
![image](https://user-images.githubusercontent.com/24975058/41857313-1b96348c-788f-11e8-8534-5c1228a47d5f.png)

This can be fixed by wrapping the light switch in it's own div.

**Comment by alexjcollins** [comment]
@lukeyouell We're going to open a issue on craftcms as giving the light switch element `min-width: 33px` sorts the problem and should hopefully help others who end up using a light switch like this.

Thanks for pointing it out!
![screen shot 2018-06-25 at 15 47 58](https://user-images.githubusercontent.com/12031196/41857504-9816e8c6-788f-11e8-89c4-054a001ddc8a.png)
![screen shot 2018-06-25 at 15 48 22](https://user-images.githubusercontent.com/12031196/41857505-9838ba5a-788f-11e8-8626-5275451c44ff.png)

**Comment by lukeyouell** [comment]
@alexjcollins setting a minimum width isn't really the solution. The problem is that the light switch doesn't work when placed immediately within an element that has `display` set to `flex`

If you wrap the light switch in another div it works.
