### ISSUE TITLE
Default Title Suffix isn't working

### ISSUE THREAD

**Issue by darylknight** [ethercreative/seo#104]
### Description
The Default Title Suffix under Settings doesn't appear to be working at all, or sometimes just unreliably. I've got a load of entries in a Pages structure in my site. Default Title Suffix is currently blank, although it's adding `| Site Name` to the end of some page titles (I previously had it set to `| Site Name`). On other entries, if I create a Default Title Suffix, it doesn't add it to page titles at all.

It may be that I'm just not clear on how this is meant to work, as I've just noticed that you can click and edit the SEO Title on a per entry basis when you've assigned the field to an entry, however - updating the Default Title Suffix has no effect on pages that are already saved. Do I need to go through every entry on the site and update them manually if the Default Title Suffix is changed at a later date?

I've also just tried adding a Default Title Suffix after clearing an entry's title, and the entire title has been overwritten by the Default Title Suffix, rather than adding it as a suffix.

### Additional info

- Craft version: 3.0.9
- SEO version: 3.2.8
- PHP version:
- Database driver & version:
- Other Plugins:

**Comment by j-greig** [comment]
Having a similar problem here.

**Comment by dannystarkDE** [comment]
Same here..

**Comment by darylknight** [comment]
Any chance of fixing this? The site in question is launching soon and all our page titles say "English"

**Comment by j-greig** [comment]
We ended up creating a custom `seo.twig` template to get around this... and just hard-coded the <title> tag to....

`<title>{{ entry.title }} - {{ seo.title }}</title>`

**Comment by alexjcollins** [comment]
Thanks for the feedback everyone. We're currently planning an update that will include functionality similar to what @j-greig is doing where we allow tokens/twig within the meta fields in the admin. Will share more when we have it.

**Comment by darylknight** [comment]
Did something similar and fleshed it out a bit:

    {% if entry is defined %}
        <title>{{ entry.title }} - {{ seo.title }}</title>
    {% elseif category is defined %}
        <title>{{ category.title }} - {{ seo.title }}</title>
    {% else %}
        <title>{{ seo.title }}</title>
    {% endif %}

**Comment by j-greig** [comment]
Any update on this?

**Comment by janhenckens** [comment]
Same issue here.

**Comment by eagleeyejack** [comment]
Any update on this?

**Comment by alexjcollins** [comment]
We're working on an update. We hope to release it soon.

**Comment by rjgux** [comment]
Any update on this?

**Comment by j-greig** [comment]
Fingers crossed for an update soon — title suffixes are one of the main reasons I use this plugin :)

**Comment by kmgdevelopment** [comment]
Still waiting for this to be fixed... Been over 6 months.

**Comment by JayBox325** [comment]
I've just installed this plugin and I have added a suffix to my Plugin settings and it's not showing in any of my pages. Still a bug for me.

**Comment by Tam** [comment]
We're ready to push an update that introduces a new and improved way of handling titles (and descriptions) in a more powerful and dynamic way, but we'd like to really put it through it's paces before we release it.

We'd really appreciate your testing and feedback, so check out [[Beta] Dynamic Meta](https://github.com/ethercreative/seo/issues/167) for more info on how you can try out the feature.
