### ISSUE TITLE
Default Social Image from SEO settings is not rendering.

### ISSUE THREAD

**Issue by moondawg69** [ethercreative/seo#105]
### Description
Default Social Image as set in SEO settings is not rendering in front end AND in the entries backend.

### Steps to reproduce

1. Clean install of the plugin, went to SEO > Settings > Default Social Image and set the image and saved. 
2. Open any entry and the image does not render on both Twitter and Facebook, placeholder is there instead.

### Additional info

- Craft version: Craft 3.0.10
- SEO version: v3.2.8
- PHP version: 7.0
- Database driver & version: 
- Other Plugins:

Also getting a depreciation error, seems like it's actually coming from that Default Social Image code as well:

Deprecation error: Looping through element queries directly has been deprecated. Use the all() function to fetch the query results before looping over them. Called from /home/websitedesigners/craft/vendor/craftcms/cms/src/elements/db/ElementQuery.php:405
--
craft\elements\db\AssetQuery::getIterator() Called from /home/websitedesigners/craft/storage/runtime/compiled_templates/77/773dab371b9ccd5353e5f7cccb4cdf6c22b2f9489c8aed918e449a34863166d0.php:74
__TwigTemplate_18bf511887de9ccccd3bf6a1f1a403403cf3cafbf17951c0a685d99601d6b534::doDisplay(["label" => "Default Social Image", "instructions" => "The image that will be used when the page is shared via social n...", "name" => "socialImage", "id" => "socialImage", ...], []) Called from /home/websitedesigners/craft/vendor/twig/twig/lib/Twig/Template.php:390

**Comment by Tam** [comment]
The fallback image doesn't render in the field, instead instructions are shown.
