### ISSUE TITLE
Using Sites is overriding all <title> settings

### ISSUE THREAD

**Issue by darylknight** [ethercreative/seo#108]
### Description
I've just set up a new Craft install, and set up a default site and a Spanish version of the site. The titles of all entries are now just showing the Site Name as defined in http://domain.test/admin/settings/sites. The English version is showing the Site Name, and when looking at the Spanish version of the site, all entry titles are just "Espanol". None of the options in the SEO plugin, or on the in-entry overrides are making any difference.

### Steps to reproduce

1. Set up two Sites
2. All `<title></title>` tags are being overridden by the site's Name.

### Additional info

- Craft version:3.0.10.3
- SEO version: 3.2.8
- PHP version: 7.1.15

**Comment by monachilada** [comment]
I'm getting exactly the same results in a similar situation.

**Comment by monachilada** [comment]
In case it helps, I created a global SEO object (in my code, referenced in the `meta` global group), and merge its settings into the entry settings if they are being left blank. I then used a custom SEO template, and replaced the logic for selecting which SEO object to use with this:

```twig
{% if seo is not defined and entry is defined and entry['seo'] is defined %}
  {% set title = entry.seo.title|default(meta.seo.title) %}
  {% set description = entry.seo.description|default(meta.seo.description) %}
  {% set twitter = entry.seo.social.twitter|default(meta.seo.social.twitter) %}
  {% set facebook = entry.seo.social.facebook|default(meta.seo.social.facebook) %}
  {% set social = {
    twitter: twitter,
    facebook: facebook
  } %}
  {% set seo = craft.seo.custom(title, description, false, social) %}
{% endif %}
{% if seo is not defined or seo is null %}
  {% set seo = meta.seo %}
{% endif %}
```

**Comment by Tam** [comment]
This is no longer an issue with our upcoming dynamic meta feature. It's currently in beta, so if you get a chance we'd really appreciate some testers! See [[Beta] Dynamic Meta](https://github.com/ethercreative/seo/issues/167) for more info.
