### ISSUE TITLE
Deprecated warning

### ISSUE THREAD

**Issue by fdelaneau** [ethercreative/seo#109]
### Description

Using the plugin as intended results in a deprecated warning for a missing .all() function.

### Steps to reproduce

1. Setup Seo with default template,
2. Create entries, 
3. Check the admin.

### Additional info

- Craft version: 3.0.11
- SEO version: 3.2.8

### Message

Looping through element queries directly has been deprecated. Use the all() function to fetch the query results before looping over them.

### Origin

/Users/sven/Sites/albert-associes.com/vendor/craftcms/cms/src/templates/_includes/forms/elementSelect.html:16

### Stack trace extract

```
__TwigTemplate_34…9d::doDisplay(["label" => "Default Social Image", "instructions" => "The image that will be used when the page is shared via social n...", "name" => "socialImage", "id" => "socialImage", ...], []) 
Called from /Users/sven/Sites/albert-associes.com/vendor/twig/twig/lib/Twig/Template.php:390
```

**Comment by rinusvandam** [comment]
Having the same issue on multiple installations when setting the Default Social Image.

## Steps to reproduce
1. Setup SEO
2. Set default image in SEO > Settings
3. Switch to other section in dashboard
4. Deprecated alert appears

## Message
Looping through element queries directly has been deprecated. Use the all() function to fetch the query results before looping over them.

## Location
craftcms/vendor/craftcms/cms/src/templates/_includes/forms/elementSelect.html:16
