### ISSUE TITLE
Default social image

### ISSUE THREAD

**Issue by alanski66** [ethercreative/seo#111]
### Steps to reproduce

1. Setup blah blah
2. Specify default social image
3. go to listings page of entries where no seo field present
4. Expecting to see default social image populating open graph tags but it doesnt show anything

How do we access this in template?

### Additional info

- Craft version:latest 3
- SEO version: latest
- PHP version: 7.1.12
- Database driver & version: mysql 5.6.38
- Other Plugins:

**Comment by Tam** [comment]
You can use [`{% set seo = craft.seo.custom() %}`](https://github.com/ethercreative/seo#custom-seo-object) to populate the SEO meta when no field is present. Currently this does not auto-populate the default social image. This is a bug, tracking in #113.
