### ISSUE TITLE
Bulk Redirects - Not working

### ISSUE THREAD

**Issue by Jdesk** [ethercreative/seo#112]
### Description

I have a spreadsheet of about 4000 redirects I need to import into the plugin.  Every time I attempt to add one (or multiple) - I get an Error and cannot add it.  Error is "SEO: An unknown error has occurred"

### Steps to reproduce

1. Something along these lines is input into bulk field:  /contact-faq      /our-work/contact-us

Multiple lines would look like this:

/partnerships   /partner-offices
/contact-faq      /our-work/contact-us

All of my redirects will follow the above structure.  

2. Seperator:  - 
I'm not sure what you mean by separator - as I just want to use a space between the two urls.   I can add a "-" between all urls, not a problem if need be.  

### Additional info

- Craft version: Craft Pro 3.0.12
- SEO version: 3.28
- PHP version: 7.0.30
- Database driver & version: MySQL 5.7.22
- Other Plugins:

**Comment by Gillon** [comment]
I'm running into this same issue on 3.3 and in my case it's related to my CDN disallowing PUT, and DELETE requests. Adding rules to allow the aforementioned HTTP Methods disables content caching, so I am stuck back at square one.

Would it be possible to have this plugin use POST instead?

**Comment by Tam** [comment]
@Jdesk The separator is the character that separates each "column" of your bulk upload. In your case that would be a space. (I've added clearer instructions to the field in the next release.) I've tested with your example and it works fine. If you're still getting the error, try uploading them in chunks of 1000 or less.

@Gillon What CDN are you using? Seems a bit weird that allowing those methods would cause an issue with your caching. I'd recommend speaking to your CDN's support to see if they can help.

**Comment by Jdesk** [comment]
@Tam thanks my friend.  worked fine.

**Comment by chadcrowell** [comment]
Same issue here, 79 redirects. I have tried bulk importing with a space and a comma and both gave me the error message. Here is my list of redirects if you want to check them out:
https://gist.github.com/chadcrowell/b1def74cfa93616c8266bc060c68f7ca

Craft 3.1.19
SEO 3.5.4

thanks.
