### ISSUE TITLE
Case (in)sensitivity in redirects?

### ISSUE THREAD

**Issue by proimage** [ethercreative/seo#116]
### Description
From what I can tell, in version 3.2.8, the Redirect management interface is case-*in*sensitive, while the actual implementation of the redirects is case-*sensitive*.

In other words, once I create a redirect from `example.com/MyAwesomePage`, I cannot then create another redirect from `example.com/myawesomepage` because it "A redirect with that URI already exists!". However, going to example.com/myawesomepage doesn't result in a redirection.

Presumably this is solvable with regexes... could someone post an example?

- Craft version: 3.0.12
- SEO version: 3.2.8

**Comment by Tam** [comment]
Fixed in [v3.4.0](https://github.com/ethercreative/seo/releases/tag/v3.4.0)

**Comment by proimage** [comment]
This still seems to be an issue (running 3.4.4). I can't add `foo` -> `bar` and then `Foo` -> `bar`; an error message says "SEO: A redirect with that URI already exists!".

**Comment by proimage** [comment]
@Tam ?

**Comment by proimage** [comment]
TY!
