### ISSUE TITLE
Use of OR operator

### ISSUE THREAD

**Issue by paragonn** [ethercreative/seo#117]
### Description
It does not seem possible to use the regex OR (|) operator.

For example, lets say I want to use regex to match against two ids:
blog?id=(1|2)

The above regex does not work.

### Steps to reproduce

1. Use the | (OR) operator to match against two or more different values

### Additional info

- Craft version: 3.0.12
- SEO version: 3.2.8
- PHP version: 7

**Comment by Tam** [comment]
Fixed in [v3.4.0](https://github.com/ethercreative/seo/releases/tag/v3.4.0)
