### ISSUE TITLE
Redirect Regex Bug 

### ISSUE THREAD

**Issue by putyourlightson** [ethercreative/seo#119]
The following line unnecessarily replaces all occurrences of `*` with `(.*)`, which means that the URI `blog(.*)` will be replaced with `blog(.(.*))`, which is obviously not the same thing. 

https://github.com/ethercreative/seo/blob/0c16162f94f2859168641f6e4f5a6906978f5d3b/src/services/RedirectsService.php#L239

Can it please be either fixed or removed? My suggestion would be simply:

`return '#^' . str_replace('/', '\/', $uri) . '#';`

SEO version: 3.3.0

**Comment by Tam** [comment]
Fixed in [v3.4.0](https://github.com/ethercreative/seo/releases/tag/v3.4.0).
