### ISSUE TITLE
Commerce 2 product support

### ISSUE THREAD

**Issue by alexhillel** [ethercreative/seo#128]
### Description
Can the plugin support Commerce 2 products? After adding the SEO field to a product, in the preview the title tag appears correctly, but on the page itself it's falling back to a default.

### Steps to reproduce

1. Add a product in Craft Commerce 2.
2. Attach the SEO field to the product.
3. Edit the product SEO field.
4. View the product on the front end and the SEO data isn't being pulled through.

### Additional info

- Craft version: 3.0.21
- SEO version: 3.3.0
- PHP version: 7.1

**Comment by nickcobley** [comment]
I'm seeing the exact behaviour here, same steps to reproduce.

**Comment by nickcobley** [comment]
Found the issue. In the default meta template lines 2-4 have:

```
	{%- if seo is not defined and entry is defined and entry["seo"] is defined and entry.seo is iterable %}
		{% set seo = entry.seo %}
	{% endif %}
```

The trouble here is Commerce uses the product element not the entries element. While I'm sure there is a more elegant solution, for now I've just create a custom meta template to override the default, with the above replaced with:

```
	{%- if seo is not defined and entry is defined and entry["seo"] is defined and entry.seo is iterable %}
		{% set seo = entry.seo %}
	{%- elseif seo is not defined and product is defined and product["seo"] is defined and product.seo is iterable %}
		{% set seo = product.seo %}
	{% endif %}
```

I'm guessing this issue would have been the same for Commerce 1 as there is nothing unique to v2 here.
