### ISSUE TITLE
Cannot reach the activation URL when this plugin is enabled

### ISSUE THREAD

**Issue by benface** [ethercreative/seo#130]
### Description

When this plugin is enabled, users who follow the activation link to set their password for the first time are greeted with this message:

<img width="281" alt="horrible" src="https://user-images.githubusercontent.com/1059139/44992149-691e8b80-af64-11e8-9fe1-88633550eef3.png">

### Steps to reproduce

1. Install this plugin.
2. Create a new user and check "send an activation email now".
3. Follow the link in the email.

### Additional info

- Craft version: 3.0.22
- SEO version: 3.3.0
- PHP version: 7.2
- Database driver & version:
- Other Plugins:

**Comment by Tam** [comment]
I can't re-create this. What other plugins are you using, and do you have any redirects that could be having an effect?

**Comment by benface** [comment]
Hey @Tam, thank you for replying. I have no redirects set up, I mostly use this plugin for the SEO field and the sitemap. Here's my log (web-404s.log) when the error happens:

[web-404s.log](https://github.com/ethercreative/seo/files/2346479/web-404s.log)

And here's my full list of plugins:

<img width="758" alt="plugins-1" src="https://user-images.githubusercontent.com/1059139/45000263-79992b00-af91-11e8-8cd7-6c0e57431d8d.png">
<img width="745" alt="plugins-2" src="https://user-images.githubusercontent.com/1059139/45000264-79992b00-af91-11e8-8805-5bdcf0094604.png">
<img width="749" alt="plugins-3" src="https://user-images.githubusercontent.com/1059139/45000265-79992b00-af91-11e8-9429-04c687d73f83.png">
<img width="748" alt="plugins-4" src="https://user-images.githubusercontent.com/1059139/45000266-79992b00-af91-11e8-9d8b-3903f6844301.png">

**Comment by Tam** [comment]
There was some wierdness going on when injecting the robots headers. I've just pushed a fix which should solve your issue. I've also deleted your previous comment due to sensitive info!

**Comment by benface** [comment]
Was there? I checked for it and saw that all the passwords and API keys had been replaced by dots! Anyway thank you so much for the quick fix!!!

**Comment by benface** [comment]
I confirm that the fix works by the way! Great job! 👍
