### ISSUE TITLE
Sitemap generates broken incorrect URLs

### ISSUE THREAD

**Issue by 99ster** [ethercreative/seo#136]
### Description
The URLs in the sitemap.xml generated by 'SEO' are in this incorrect format (404 errors):

`<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml">
<sitemap>
<loc>
https://dev.site.com/en/sitemap_sections_15_0.xml
</loc>
<lastmod>2018-09-04T10:36:12+01:00</lastmod>
</sitemap>
<sitemap>
<loc>
https://dev.site.com/en/sitemap_sections_23_0.xml
</loc>
<lastmod>2018-09-04T10:36:12+01:00</lastmod>
</sitemap>
</sitemapindex> `

### Steps to reproduce

1. Enable a 'section' in the SEO control panel and save.

### Additional info

- Craft version: 3.0.23.1
- SEO version: 3.4.3
- PHP version: 7.0.31
- Database driver & version: MySQL 5.5.60
- Other Plugins: Redactor, Freeform Pro, Sprout Active

**Comment by Tam** [comment]
I've just pushed an update fixing a server error when generating the "sub" sitemaps. Could you try it out and see if it helps?

**Comment by 99ster** [comment]
Many thanks for responding so quickly - it's much appreciated.

Applied the updated (to version 3.4.4), but unfortunately, the generated sitemap.xml file is still full of 404 URLs in this format:

`<loc>
https://dev.site.com/sk/sitemap_sections_23_0.xml
</loc>`

**Comment by Tam** [comment]
Do you have any templates or routes that could be overriding the sitemap urls?

**Comment by 99ster** [comment]
The only route is the usual one for the search results template.

I'm seeing this same error on two Craft 3 websites, one is really quite simple, with nothing exotic in the templates at all.  And the second site is multi-lingual, so has more going on, but nothing that is doing any odd routing in the templates that I can see....

**Comment by 99ster** [comment]
One other thing, that may be helpful...?

I only see these options in the control panel:

<img width="1415" alt="screen shot 2018-09-10 at 11 09 18" src="https://user-images.githubusercontent.com/26082907/45291460-258acb00-b4ea-11e8-8358-caea740dbc1f.png">

**Comment by Tam** [comment]
Ah, you need to check the "Enabled?" check box for them to work (everything is disabled by default). It's weird that any URLs are being output if they're all disabled.

**Comment by 99ster** [comment]
Sorry, that's a very recent screen grab taken after I switched off the 'enabled' button!   I don't want these garbage sitemap.xml files 'live'!

Of course I totally understand that you need to click the 'Enabled' check box!!!!

I posted that screen grab to just question why the control panel is missing all the options and controls shown in your screen grabs in the documentation...

Thanks.

**Comment by Tam** [comment]
The docs screen shot is a bit out of date, everything in your screenshot is up-to-date. Could you visit one of the 404'ing URLs and send me the error you get in your `web-404s.log`?

**Comment by 99ster** [comment]
Ok - will do.  Thanks.

**Comment by 99ster** [comment]
They're not actually 404 errors.  

Where it should be inserting the <loc> page URL, it's inserting the URL of an individual XML record:

`<sitemap>
<loc>
https://dev.website.com/en/sitemap_sections_15_0.xml
</loc>
<lastmod>2018-09-04T10:36:12+01:00</lastmod>
</sitemap>`

Follow this and you get:
https://dev.website.com/en/applications2018-09-04T16:49:11+01:00weekly0.5

So, the plugin is generating multiple XML records, one for each page of the site that's being 'enabled' and included in the sitemap.XML file.  Then it's listing all these in the sitemap.xml file instead of the actual page URLs.

**Comment by Tam** [comment]
Sounds like the sitemap is working correctly! If you inspect the URL you'll see it's valid XML markup, your browser just doesn't know how to render it.

To prevent unnecessary load on servers for large sites the sitemap is split into chunks. Each chunk is made up of a single entry section (or category, product, etc.) which is then split into chunks of 1000 elements in that section per sitemap.

The URL format basically translates like this: 
- `sitemap_sections_15_0.xml`
- Section w/ ID 15, Chunk 0 - This is the first 1000 elements in the section with ID 15.

If you paste any of the sitemap URLs into a sitemap validator, you'll see that they all validate correctly.

Hope that all makes sense!

**Comment by 99ster** [comment]
Great - thanks for the explanation.  Much appreciated.
