### ISSUE TITLE
Internet Explorer 11 "Social" and "Advanced" Tab not clickable

### ISSUE THREAD

**Issue by rocknrolaf** [ethercreative/seo#138]
### Description

for a client we need ie11 functionality and it seems that some es6 javascript functionalities won't work.

### Steps to reproduce

1. click on the "Social" or "Advanced" tab of your SEO field.
2. the tab won't open...

from the error message i found out its the missing Object.entries function: https://github.com/ethercreative/seo/blob/0c16162f94f2859168641f6e4f5a6906978f5d3b/resources/js/_helpers/createElement.js#L21
but after adding a polyfill in my code i think also the "let" instruction within the for loop causes problems (see: https://stackoverflow.com/questions/39159669/let-statement-in-loop-doesnt-work-as-expected-in-ie). maybe there are more issues...

### Additional info

- Craft version: Craft Pro 3.0.20
- SEO version: 3.4.4
- PHP version: 7.1.14
- Database driver & version: MySQL 5.5.5

**Comment by Tam** [comment]
The SEO admin does not support IE11 (all front-end generated code does however).
