### ISSUE TITLE
[FR] Support commerce products, variants in sitemap settings

### ISSUE THREAD

**Issue by terraindesign** [ethercreative/seo#141]
Unless I'm missing something, is doesn't seem to allow the ability to manage products and variants in the sitemap settings.

**Comment by billythekid** [comment]
I see this has the v3.5.0 milestone tag on it. Any idea when (or if) these elements will be available in sitemap?

**Comment by Wiejeben** [comment]
@billythekid It *had* the `v3.5.0` tag. Seems to had been removed.

Screenshots right now communicate as if Craft Commerce is supported for the sitemap generation, which is probably confusing.

**Comment by maartenheideman** [comment]
Does there come support for craftcommerce products in the sitemaps? Or is there a workaround to fix that?

**Comment by boboldehampsink** [comment]
Added this in #333
