### ISSUE TITLE
Global description

### ISSUE THREAD

**Issue by piotrpog** [ethercreative/seo#144]
I think there should be option in settings for global meta description value.
This value would be used if no description for specific entry would be provided.

**Comment by SteadfastCollective** [comment]
+1 for this, id assume this is possible with a custom meta template, but not sure exactly how to get that working as its not detailed very well in the readme.

**Comment by MikeHarrison** [comment]
Hi,

I have used a custom meta template for this. I added the following folder / file in `templates`: `_seo/meta.twig`

Then copied the default template from here: [https://github.com/ethercreative/seo/blob/v3/src/templates/_seo/meta.twig](https://github.com/ethercreative/seo/blob/v3/src/templates/_seo/meta.twig)

And added the following if statement around the description (you can do the same around the facebook and twitter ones too):

```
  {% if seo.description == '' %}
  <meta name="description" content="I am the global description" />
  {% else %}
    <meta name="description" content="{{ seo.description }}" />
  {% endif %}
```

Then in the settings add `_seo/meta.twig` to the _SEO Meta Template_ field

**Comment by Tam** [comment]
This is resolved with our upcoming dynamic meta feature. It's currently in beta, so if you get a chance we'd really appreciate some testers! See [[Beta] Dynamic Meta](https://github.com/ethercreative/seo/issues/167) for more info.
