### ISSUE TITLE
How Does the Keywords Feature Work?

### ISSUE THREAD

**Issue by kmgdevelopment** [ethercreative/seo#146]
I'm trying to get the keyword scoring to work, but I keep getting the message "You don't have any content, adding some would be a good start!" The entry has fields with content (Redactor), so I don't really know what it's looking for to generate a keyword score. Can you point me in the right direction?

**Comment by alexjcollins** [comment]
@kgrote The page analysis is performed on the live preview; it looks through all the output content on the rendered template. That means if your template isn't outputting all the content then SEO won't be able to read it.

**Comment by kmgdevelopment** [comment]
Ah, good to know! Thanks!
