### ISSUE TITLE
Social images not showing

### ISSUE THREAD

**Issue by Tim-Wils** [ethercreative/seo#147]
### Description
Image in fieldtype.twig .seo--social-preview-image has a relative path and that's why it's not showing. The same goes for the SEO template hook.

### Steps to reproduce

1. Upload social images in the SEO field.
2. The cms shows the relative path
3. On the front-end the image is not parsed

#fix for the seo-template on the front-end:
Use {{ alias(craft.app.sites.primarySite.baseUrl) }}{{ craft.seo.facebookImage(seo.social.facebook.image) }}
instead of {{ craft.seo.facebookImage(fb.image) }}

**Comment by Tam** [comment]
Closing as this no longer appears to be an issue.
