### ISSUE TITLE
Javascript Error on Bulk Redirect Import

### ISSUE THREAD

**Issue by kmgdevelopment** [ethercreative/seo#154]
### Description
When running a bulk redirect import, the loading spinner displays infinitely and the console throws the following error:

```
Redirects.js:157 Uncaught TypeError: Cannot read property 'appendChild' of undefined
    at Redirects.js:157
    at Array.forEach (<anonymous>)
    at Redirects.js:156
    at Object.<anonymous> (Redirects.js:303)
    at c (jquery.js:3317)
    at Object.fireWith [as resolveWith] (jquery.js:3447)
    at l (jquery.js:9272)
    at XMLHttpRequest.<anonymous> (jquery.js:9514)
(anonymous) @ Redirects.js:157
(anonymous) @ Redirects.js:156
(anonymous) @ Redirects.js:303
c @ jquery.js:3317
fireWith @ jquery.js:3447
l @ jquery.js:9272
(anonymous) @ jquery.js:9514
load (async)
send @ jquery.js:9533
ajax @ jquery.js:9173
value @ Redirects.js:296
onSubmitBulk @ Redirects.js:150

```

The redirects seem to be imported correctly after refreshing the page, just looks like the UI is broken.

### Steps to reproduce

1. Add redirects to Bulk Redirects textarea
2. Click "Add Redirects" button

### Additional info

Craft version: 3.0.32
SEO version: 3.4.4
PHP version: 7.1.12
Database driver & version: MySQL 5.6.38
Other Plugins:
Amazon S3	1.0.8
Entry Instructions	1.0.4
Imager	v2.1.1
Redactor	2.1.6
Sprout Import	1.0.0-beta.18
Super Table	2.0.14

**Comment by mylesthedev** [comment]
Also getting this

**Comment by juban** [comment]
Same here.
`TypeError: undefined is not an object (evaluating 'r.tables[l.value].appendChild')`
Sounds it's an out of range issue.

**Comment by satcreative** [comment]
I'm experiencing this issue. Any ideas what's causing it?

**Comment by proimage** [comment]
Same here, although for me it seems to prevent adding bulk redirects entirely. :-/

**Comment by jmauzyk** [comment]
Experiencing this as well. For me it looks like the redirects are saved to the `seo_redirects` table, but they do not work, nor do they show up after refreshing the Redirects CP page.

@ethercreative any idea when this issue might be resolved? Getting close to wrapping up a Craft 3 build and would love to be able to use this plugin for both SEO and redirects right off the bat.

**Comment by jmauzyk** [comment]
@Tam Appreciate the work on this. Unfortunately, while 3.6.1 solved the javascript error and the bulk add form now works, the redirects added using that form do not. For example if I add `contact-us,form/contact-us,301` using the bulk redirect form and then go to mysite.com/contact-us, I get a 404. However, if I add the same redirect using the single add redirect form at the top of the page, it will correctly redirect.

**Comment by jmauzyk** [comment]
@Tam Looked into this a bit more and I think I figured out what is wrong. Looks like when a redirect is added using the bulk add form with the site field set to "All Sites" it saves the siteId in the database as 0 instead of NULL.
