### ISSUE TITLE
** Question ** Where are the generated keywords??

### ISSUE THREAD

**Issue by zzseba78** [ethercreative/seo#155]
### Description
I can´t see the created keywords in the page, it doesn´t appear on the meta template either, what i´m missing?

**Comment by alexjcollins** [comment]
Hi @zzseba78 

Good question; for a long time Google has stated it [doesn't use keywords as a ranking factor](https://webmasters.googleblog.com/2009/09/google-does-not-use-keywords-meta-tag.html), so we decided early on that the keyword feature in the admin should only be used as a tool for analysing the page content to help authors hit some of the key things Google (and others) might be looking for in a quality page.

We also have longterm plans for the keyword section that would expand its utility within the admin for authors and also SEMs.

**Comment by zzseba78** [comment]
@alexjcollins Thanks for your reply, yes i know that google doens´t use keywords but i didn´t understand why so many effort in the UI to show them, now it´s cristal clear.

This plugin it´s great, clean and simple, but unfortunately i can´t understand how can i rewrite, for example the title for specific entries ( like sections items list ) that i get empty titles.

I check the doc info but i didn´t understand it, is there a clear example how can i do this in the template, like `{% set seotitle = "Section Title" %}`
 Thank you
