### ISSUE TITLE
Advanced tags not working

### ISSUE THREAD

**Issue by Michael-Reich** [ethercreative/seo#157]
### Description

Advanced settings aren't working. We set the noindex tag in the Advanced tab but it does not show up in the code. All other tags are working (title, description)

See here: https://digitalwunder.io/datenschutz

### Steps to reproduce

1.
2.

### Additional info

- Craft version:
- SEO version:
- PHP version:
- Database driver & version:
- Other Plugins:

**Comment by Tam** [comment]
The robots are currently output in the `X-Robots-Tag` header, but they will now be output as meta tags in the header in the next release.

**Comment by Michael-Reich** [comment]
Thank you!
