### ISSUE TITLE
Empty/blank sitemap

### ISSUE THREAD

**Issue by j-greig** [ethercreative/seo#158]
### Description

Sitemap only contains a single line:
`<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml"/>`

Have tried changing the sitemap URL so that a fresh sitemap is generated, sitemap is still empty though?

Thanks :)

### Additional info

- Craft version: 3.0.32
- SEO version: 3.4.4
- PHP version: 7.1

**Comment by j-greig** [comment]
Ermmmm I might have forgotten to enable the sections I wanted to include at admin/seo/sitemap 😊

**Comment by brandondeweese** [comment]
I'm having this exact problem.

https://scalecomputing.com/sitemap.xml

Craft Pro 3.5.16
PHP 7.4.3
SEO 3.6.7

It's only generating this line:

`<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml"/>`
