### ISSUE TITLE
Generated robots.txt file has HTTP status 404

### ISSUE THREAD

**Issue by thijskaspers** [ethercreative/seo#159]
The generated robots.txt works just fine (it is reachable and content is visible), but somehow the HTTP status it has is 404, while it should be 200?

### Additional info

- Craft version: 3.0.34
- SEO version: 3.4.4
- PHP version: 7.2.12
- Database driver: mariadb

**Comment by thijskaspers** [comment]
Can anyone else confirm they get a 404 statuscode from their generated robots.txt file too?

This is strange behavior. When I dump the Yii response, it shows the headers and a correct statuscode of 200, but somehow the response ends up being a 404. Craft/Yii related issue?

Will try it with xdebug later on to see where the response gets altered.

**Comment by Tam** [comment]
I can't recreate this, could you share any error logs you have related to the issue?

**Comment by adamskyle** [comment]
@thijskaspers 

We had the same issue, turned out we had a location /robots.txt rule in our nginx configuration, that conflicts with the Craft rewrite. When we removed the custom location rule from nginx, the robots.txt gave a 200 status code.
