### ISSUE TITLE
SEO Template Doesn't Display for Pending or Expired Entries

### ISSUE THREAD

**Issue by kmgdevelopment** [ethercreative/seo#163]
### Description
If an entry is pending or expired, the SEO template does not display. I have an events section on my site so I still need SEO tags even if the entries are not 'live'.

### Steps to reproduce

1. Add SEO field to section
2. Publish entry with future date.
3. Access entry on front-end

### Additional info

- Craft version: 3.0.36
- SEO version: 3.4.4

**Comment by alexjcollins** [comment]
Hi @kgrote so are you forcing the entries to be visible on the front-end even with those entry statuses?

**Comment by kmgdevelopment** [comment]
Yes, that's right. Events are upcoming and expire but still need to display.

**Comment by Tam** [comment]
This appears to be resolved with our upcoming dynamic meta feature. It's currently in beta, so if you get a chance we'd really appreciate some testers! See [[Beta] Dynamic Meta](https://github.com/ethercreative/seo/issues/167) for more info.
