### ISSUE TITLE
Social titles not created live

### ISSUE THREAD

**Issue by billythekid** [ethercreative/seo#164]
### Description

When creating a new entry with an SEO field in it's fieldlayout the SEO title is automatically generated. The same title however is not applied to the facebook/twitter parts of the field, all those get is the default suffix if any.

### Steps to reproduce

1. Create a new entry, give it a title
2. See the title in the optimisation part of the SEO field and not in the social ones

### Additional info

- Craft version: 3.0.36
- SEO version: 3.4.4
- PHP version: 7.2.13
- Database driver & version: MySQL 5.6.42
- Other Plugins: Reedactor, Retour, Contact form, contact form honeypot

**Comment by AlexandreKilian** [comment]
Please let me know if you find a fix, I have the same issue with one of my sites… weirdly, it works just fine on all my other craft sites…

**Comment by Tam** [comment]
This should be fixed in [v3.5.0](https://github.com/ethercreative/seo/releases/tag/v3.5.0)
