### ISSUE TITLE
Optimisation title duplicated on invalid save.

### ISSUE THREAD

**Issue by billythekid** [ethercreative/seo#165]
### Description
If you create an entry which has an SEO field in its fieldlayout and it fails validation on save, the auto-populated title in the optimisation part of the SEO field gets the saved title as a suffix, leading to a duplication in the title. 

### Steps to reproduce

1. Create an entry type with two fields, one an SEO field, one anything else, a plain text for example. Make the plain text field a required field.
2. Create a new entry of this type and give it a title, observe this title carried through to the SEO field (along with any default suffix). Don't fill in the required field and hit save.
3. Observe the title duplicated in the SEO field at this time (as if the pre-save value is added as a suffix to the whole title)

### Additional info

- Craft version: 3.0.36
- SEO version: 3.4.4
- PHP version: 7.2.13
- Database driver & version: MySQL 5.6.42
- Other Plugins: Redactor, Retour, Contact Form, Contact Form Honeypot

**Comment by Tam** [comment]
This should be resolved with our upcoming dynamic meta feature. It's currently in beta, so if you get a chance we'd really appreciate some testers! See[[Beta] Dynamic Meta](https://github.com/ethercreative/seo/issues/167) for more info.
