### ISSUE TITLE
Redirect with plus symbol

### ISSUE THREAD

**Issue by hatzipanis** [ethercreative/seo#166]
### Description

Sorry if this is stupidly easy to resolve. I'm trying to create a redirect for `Sun+protection.html` but I get the Craft template not found message instead of the redirect:

> Template not found: Sun protection.html

### Steps to reproduce

1. Create a redirect for: `Sun+protection.html`
2. Visit the URL
3. Cry 😭
4. Thank the maintainer any way for the great work developing this free plugin 🎉

### Additional info

- Craft version: 3.0.36
- SEO version: 3.4.4

**Comment by Tam** [comment]
Can you try escaping the `+` with a back slash: `Sun\+protection.html`?

**Comment by Tam** [comment]
@hatzipanis Craft reads `+` as a space, so creating a redirect for `Sun protection.html` will work.
