### ISSUE TITLE
Optimisation Checklist not working on Craft 3.1.1

### ISSUE THREAD

**Issue by harebuus** [ethercreative/seo#168]
### Description

Optimisation Checklist not working on Craft 3.1.1
Error Message: "SEO: Failed to retrieve entry preview"

### Steps to reproduce

1. Add keyword to entry
2. Click on keyword

### Additional info

- Craft version: Craft Solo 3.1.1
- SEO version: 3.4.4
- PHP version: 7.2.10
- Database driver & version: MySQL 10.1.37
- Other Plugins:

**Comment by Tam** [comment]
This is fixed on the dev branch, which is due to be released next Monday along with the new [[Beta] Dynamic Meta](https://github.com/ethercreative/seo/issues/167).

**Comment by ghost** [comment]
Doesn't seem to work for me. I get a red "SEO: Failed to retrieve entry preview"  and in the optimization checklist "You don't have any content, adding some would be a good start!"
 Can' find any other errors related to this.

**Comment by ghost** [comment]
Maybe this is not related to the SEO plugin? My craft live preview also just returns a blank screen, so maybe something else broke, I'll investigate.

**Comment by Tam** [comment]
@mgrandl SEO now requires Craft 3.1.0 or later due to changes in how live preview works.

**Comment by ghost** [comment]
@Tam I know I am on Craft 3.1.2.2 but apparently the craft update broke my live preview or something.

**Comment by ghost** [comment]
@Tam ok nevermind the plugin works as expected. I figured it out and it's just my weird staging environment...
