### ISSUE TITLE
Character from siteName appears as HTML entity in title tag

### ISSUE THREAD

**Issue by ccchapman** [ethercreative/seo#173]
### Description

My `siteName` contains a single quote character (`'`). After upgrading `ether/seo`, from 3.4.4, the single quote appears as an HTML entity in my markup.

This also appears in title meta elements, such as `og:title`.

```
<title>Home | Where&amp;#039;s Wally?</title>
```

### Steps to reproduce

1. Have an installation with a single quote character in the `siteName` and use the `siteName` in your SEO title suffix
2. Upgrade `ether/seo` and inspect the page

### Additional info

- Craft version: 3.1.2.2
- SEO version: 3.5.1
- PHP version: 7.2

cc @Tam

**Comment by sctgraham** [comment]
I have this problem also despite having a version later than the fix referenced above. I've tried adding `raw`twig filters, but this doesn't affect the result in any way. Thanks for your help !
