### ISSUE TITLE
Setting unknown property: ether\seo\models\data\SeoData::id

### ISSUE THREAD

**Issue by shgzon** [ethercreative/seo#174]
### Description

Some pages still don't open after updating [172](https://github.com/ethercreative/seo/issues/172). 

Updating manually is not working for me. Gives error: `Unknown command: seo/upgrade/to-new-data-format`.

### Steps to reproduce

1. Update your plug-in
2. Try to edit the page in the admin panel

### Additional info

Error logs:
```
2019-01-21 19:57:06 [-][1][-][error][craft\queue\QueueLogBehavior::afterError]  [1] Upgrading entry elements SEO data (attempt: 1) - Error (time: 1.519s): Setting unknown property: ether\seo\models\data\SeoData::id
2019-01-21 19:57:06 [-][1][-][error][yii\base\UnknownPropertyException] yii\base\UnknownPropertyException: Setting unknown property: ether\seo\models\data\SeoData::id in /vendor/yiisoft/yii2/base/BaseObject.php:163

#0 vendor/yiisoft/yii2/BaseYii.php(546): yii\base\BaseObject->__set('id', NULL)
#1 vendor/yiisoft/yii2/base/BaseObject.php(107): yii\BaseYii::configure(Object(ether\seo\models\data\SeoData), Array)
#2 vendor/ether/seo/src/models/data/SeoData.php(193): yii\base\BaseObject->__construct(Array)
#3 vendor/ether/seo/src/fields/SeoField.php(101): ether\seo\models\data\SeoData->__construct(Object(ether\seo\fields\SeoField), Object(craft\elements\Entry), Array)
#4 vendor/craftcms/cms/src/base/Element.php(2007): ether\seo\fields\SeoField->normalizeValue(Array, Object(craft\elements\Entry))
#5 vendor/craftcms/cms/src/base/Element.php(826): craft\base\Element->normalizeFieldValue('seo')
#6 vendor/yiisoft/yii2/base/ArrayableTrait.php(126): craft\base\Element->__get('seo')
#7 vendor/craftcms/cms/src/web/View.php(503): yii\base\Model->toArray(Array, Array, false)
#8 vendor/craftcms/cms/src/elements/Entry.php(992): craft\web\View->renderObjectTemplate('{{ (_variables....', Object(craft\elements\Entry))
#9 vendor/craftcms/cms/src/elements/Entry.php(1052): craft\elements\Entry->updateTitle()
#10 vendor/craftcms/cms/src/services/Elements.php(403): craft\elements\Entry->beforeSave(false)
#11 vendor/craftcms/cms/src/queue/jobs/ResaveElements.php(73): craft\services\Elements->saveElement(Object(craft\elements\Entry))
#12 vendor/yiisoft/yii2-queue/src/Queue.php(214): craft\queue\jobs\ResaveElements->execute(Object(craft\queue\Queue))
#13 vendor/yiisoft/yii2-queue/src/cli/Queue.php(147): yii\queue\Queue->handleMessage('46', 'O:31:"craft\\que...', '300', 1)
#14 vendor/craftcms/cms/src/queue/Queue.php(96): yii\queue\cli\Queue->handleMessage('46', 'O:31:"craft\\que...', '300', 1)
#15 vendor/craftcms/cms/src/controllers/QueueController.php(86): craft\queue\Queue->run()
#16 [internal function]: craft\controllers\QueueController->actionRun()
#17 vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#18 vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#19 vendor/craftcms/cms/src/web/Controller.php(109): yii\base\Controller->runAction('run', Array)
#20 vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('run', Array)
#21 vendor/craftcms/cms/src/web/Application.php(297): yii\base\Module->runAction('queue/run', Array)
#22 vendor/craftcms/cms/src/web/Application.php(561): craft\web\Application->runAction('queue/run', Array)
#23 vendor/craftcms/cms/src/web/Application.php(281): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#24 vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#25 web/index.php(21): yii\base\Application->run()
#26 {main}
#26 {main}
```

- Craft version: 3.1.2.2
- SEO version: 3.5.1
- PHP version:
- Database driver & version:
- Other Plugins:

**Comment by Tam** [comment]
Is there more to that error log? There's usually a stacktrace with more detail after it.

When you run `./craft help` do you see the SEO command listed?

**Comment by shgzon** [comment]
Oh I am sorry, I added the stacktrace in the above message (by editing that message).

And I don't see the SEO command.. any ideas how to resolve?

Could it be something with using {title} and in some entries using a custom field e.g. {customTitle}. Because all my Singles are working, only Structures or Channels are broken...

**Comment by Tam** [comment]
Could you try uninstalling and reinstalling the plugin through composer (don't need to do anything in Craft)? 
`composer remove ether/seo && composer require ether/seo`

I'm not sure why it's trying to set `id`, that's not a value the SEO field has ever stored. Could you send me the data of the SEO field in of the entries that's erroring? You can find it in the `content` table of your database.

**Comment by shgzon** [comment]
Could it be that I ever used SEOmatic?

This is the content of two of the fields:

``
{"id":null,"enabled":1,"archived":0,"locale":"en_US","localeEnabled":1,"slug":null,"uri":null,"dateCreated":null,"dateUpdated":null,"root":null,"lft":null,"rgt":null,"level":null,"searchScore":null,"elementId":0,"metaType":"template","metaPath":"","seoMainEntityCategory":"Organization","seoMainEntityOfPage":"MovingCompany","seoTitle":"Consultancy","seoDescription":"Consultancy","seoKeywords":"Consultancy","seoImageTransform":"openGraphImage","seoFacebookImageTransform":"openGraphImage","seoTwitterImageTransform":"openGraphImage","twitterCardType":"summary_large_image","openGraphType":"website","robots":"all","seoImageId":"239","seoTwitterImageId":"","seoFacebookImageId":"239","canonicalUrlOverride":"","seoTitleUnparsed":"Consultancy","seoDescriptionUnparsed":"Consultancy","seoKeywordsUnparsed":"Consultancy","seoTitleSource":"field","seoTitleSourceField":"title","seoDescriptionSource":"field","seoDescriptionSourceField":"title","seoKeywordsSource":"field","seoKeywordsSourceField":"title","seoImageIdSource":"field","seoImageIdSourceField":"bannerAfbeelding","seoTwitterImageIdSource":"custom","seoTwitterImageIdSourceField":"bannerAfbeelding","seoFacebookImageIdSource":"field","seoFacebookImageIdSourceField":"bannerAfbeelding","seoCommerceVariants":null,"__model__":"Craft\\Seomatic_MetaFieldModel"}``

And
``
{"titleRaw":["Enjoy a carefree move! | Move4U - Delivering moving software"],"descriptionRaw":"","keywords":[],"score":"","social":{"twitter":{"handle":"","title":"Enjoy a carefree move! | Move4U - Delivering moving software","image":{"volumeId":"1","folderId":"1","folderPath":"","filename":"move4u-og_image.png","kind":"image","size":"29454","keptFile":null,"dateModified":"2018-10-15T13:09:27+02:00","newLocation":null,"locationError":null,"newFilename":null,"newFolderId":null,"tempFilePath":null,"avoidFilenameConflicts":false,"suggestedFilename":null,"conflictingFilename":null,"deletedWithVolume":false,"keepFileOnDelete":false,"id":"1138","tempId":null,"uid":"9e682230-a63d-40c4-b29c-ee7da2d1d1ae","fieldLayoutId":"412","contentId":"515","enabled":"1","archived":"0","siteId":"1","enabledForSite":"1","title":"Move4U Og Image","slug":null,"uri":null,"dateCreated":"2018-10-15T13:09:22+02:00","dateUpdated":"2019-01-21T15:30:08+01:00","trashed":false,"duplicateOf":null,"hasDescendants":false,"ref":null,"status":"enabled","structureId":null,"totalDescendants":0,"url":"https://dev.move4u.com/uploads/media/move4u-og_image.png","extension":"png","focalPoint":{"x":0.5,"y":0.5},"hasFocalPoint":false,"height":"1200","mimeType":"image/png","path":"move4u-og_image.png","width":"1200"},"description":""},"facebook":{"handle":"","title":"Enjoy a carefree move! | Move4U - Delivering moving software","image":{"volumeId":"1","folderId":"1","folderPath":"","filename":"move4u-og_image.png","kind":"image","size":"29454","keptFile":null,"dateModified":"2018-10-15T13:09:27+02:00","newLocation":null,"locationError":null,"newFilename":null,"newFolderId":null,"tempFilePath":null,"avoidFilenameConflicts":false,"suggestedFilename":null,"conflictingFilename":null,"deletedWithVolume":false,"keepFileOnDelete":false,"id":"1138","tempId":null,"uid":"9e682230-a63d-40c4-b29c-ee7da2d1d1ae","fieldLayoutId":"412","contentId":"515","enabled":"1","archived":"0","siteId":"1","enabledForSite":"1","title":"Move4U Og Image","slug":null,"uri":null,"dateCreated":"2018-10-15T13:09:22+02:00","dateUpdated":"2019-01-21T15:30:08+01:00","trashed":false,"duplicateOf":null,"hasDescendants":false,"ref":null,"status":"enabled","structureId":null,"totalDescendants":0,"url":"https://dev.move4u.com/uploads/media/move4u-og_image.png","extension":"png","focalPoint":{"x":0.5,"y":0.5},"hasFocalPoint":false,"height":"1200","mimeType":"image/png","path":"move4u-og_image.png","width":"1200"},"description":""}},"advanced":{"robots":[],"canonical":null}}``

``{"title":"Blog | Move4U - Delivering moving software","description":"","keywords":[],"score":"","social":{"twitter":{"handle":"","title":"Blog | Move4U - Delivering moving software","image":{"volumeId":"1","folderId":"1","folderPath":"","filename":"move4u-og_image.png","kind":"image","size":"29454","keptFile":null,"dateModified":"2018-10-15T13:09:27+02:00","newLocation":null,"locationError":null,"newFilename":null,"newFolderId":null,"tempFilePath":null,"avoidFilenameConflicts":false,"suggestedFilename":null,"conflictingFilename":null,"deletedWithVolume":false,"keepFileOnDelete":false,"id":"1138","tempId":null,"uid":"9e682230-a63d-40c4-b29c-ee7da2d1d1ae","fieldLayoutId":"412","contentId":"515","enabled":"1","archived":"0","siteId":"1","enabledForSite":"1","title":"Move4U Og Image","slug":null,"uri":null,"dateCreated":"2018-10-15T13:09:22+02:00","dateUpdated":"2018-10-15T14:36:23+02:00","trashed":false,"duplicateOf":null,"hasDescendants":false,"ref":null,"status":"enabled","structureId":null,"totalDescendants":0,"url":"move4u-og_image.png","extension":"png","focalPoint":{"x":0.5,"y":0.5},"hasFocalPoint":false,"height":"1200","mimeType":"image/png","path":"move4u-og_image.png","width":"1200"},"description":""},"facebook":{"handle":"","title":"Blog | Move4U - Delivering moving software","image":{"volumeId":"1","folderId":"1","folderPath":"","filename":"move4u-og_image.png","kind":"image","size":"29454","keptFile":null,"dateModified":"2018-10-15T13:09:27+02:00","newLocation":null,"locationError":null,"newFilename":null,"newFolderId":null,"tempFilePath":null,"avoidFilenameConflicts":false,"suggestedFilename":null,"conflictingFilename":null,"deletedWithVolume":false,"keepFileOnDelete":false,"id":"1138","tempId":null,"uid":"9e682230-a63d-40c4-b29c-ee7da2d1d1ae","fieldLayoutId":"412","contentId":"515","enabled":"1","archived":"0","siteId":"1","enabledForSite":"1","title":"Move4U Og Image","slug":null,"uri":null,"dateCreated":"2018-10-15T13:09:22+02:00","dateUpdated":"2018-10-15T14:36:23+02:00","trashed":false,"duplicateOf":null,"hasDescendants":false,"ref":null,"status":"enabled","structureId":null,"totalDescendants":0,"url":"move4u-og_image.png","extension":"png","focalPoint":{"x":0.5,"y":0.5},"hasFocalPoint":false,"height":"1200","mimeType":"image/png","path":"move4u-og_image.png","width":"1200"},"description":""}},"advanced":{"robots":[]}}``

**Comment by shgzon** [comment]
I think it has something to do with the title format. Sometimes you will be using {section.name|raw} as title and sometimes this is a custom field like {customTitle}. It seems that where this is the case the sections get bugged.

**Comment by rolfkokkeler** [comment]
it seems that the conversion of the seomatic data to seo data failed for some entries, all entries starting with

>  {"titleRaw":{

 are fine, but all starting with

>  {"title":"

 fail to open in the CP and on the frontend.

**Comment by Tam** [comment]
@shgzon Are you using the same field that used to be SEOmatic? SEO doesn't have support for SEOmatic field data so you'll want to create a new SEO field and use that.

**Comment by shgzon** [comment]
@Tam correct! I've just cleared the fields with strange values within the database `craft_content` -> `field_seo` (for me).

Now it's fixed.

**Comment by Tam** [comment]
@shgzon Glad to hear, closing this issue.
