### ISSUE TITLE
sitemap returns Internal Server Error - 500 - PHP Notice 'yii\base\ErrorException' with message 'Undefined index: titleRaw'

### ISSUE THREAD

**Issue by JoshMustafa** [ethercreative/seo#178]
### Description

This XML file does not appear to have any style information associated with it. The document tree is shown below.
<response>
<name>Internal Server Error</name>
<message>An internal server error occurred.</message>
<code>0</code>
<status>500</status>
</response>

### Additional info

- Craft version:Craft Pro 3.1.3
- SEO version:3.5.2
- PHP version:7.2.13
- Database driver & version:MySQL 5.5.60

Was working before the update. Not sure if theres something else i should be updating?

**Comment by JoshMustafa** [comment]
Just found out its something to do with this ...

PHP Notice 'yii\base\ErrorException' with message 'Undefined index: titleRaw'

**Comment by ryanscherler** [comment]
Getting this same message when just trying to add a new entry.

**Comment by 23d1** [comment]
Getting the same issue simply trying to load CSS-files. Whether it's loading as a link or directly navigating to the css-file;

```
PHP Notice 'yii\base\ErrorException' with message 'Undefined index: titleRaw' 

in /craft/vendor/ether/seo/src/models/data/SeoData.php:143

Stack trace:
#0 /craft/vendor/craftcms/cms/src/web/ErrorHandler.php(76): yii\base\ErrorHandler->handleError(8, 'Undefined index...', '/Sites/...', 143)
#1 /craft/vendor/ether/seo/src/models/data/SeoData.php(143): craft\web\ErrorHandler->handleError(8, 'Undefined index...', '/Sites/...', 143, Array)
#2 /craft/vendor/ether/seo/src/services/SeoService.php(113): ether\seo\models\data\SeoData->__construct()
#3 /craft/vendor/ether/seo/src/services/SeoService.php(57): ether\seo\services\SeoService->_getElementAndSeoFields()
#4 /craft/vendor/ether/seo/src/Seo.php(300): ether\seo\services\SeoService->injectCanonical()
#5 [internal function]: ether\seo\Seo->onAfterRequest(Object(yii\base\Event))
#6 /craft/vendor/yiisoft/yii2/base/Event.php(310): call_user_func(Array, Object(yii\base\Event))
#7 /craft/vendor/yiisoft/yii2/base/Component.php(636): yii\base\Event::trigger('craft\\web\\Appli...', 'afterRequest', Object(yii\base\Event))
#8 /craft/vendor/yiisoft/yii2/base/Application.php(389): yii\base\Component->trigger('afterRequest')
#9 /web/index.php(21): yii\base\Application->run()
```

Tested on multiple installs.
