### ISSUE TITLE
Custom 

### ISSUE THREAD

**Issue by NicolasBarse** [ethercreative/seo#179]

**Comment by NicolasBarse** [comment]
Hi,

I'm quite a twig and craft rookie and I'm trying to set-up the custom fields for couple unique pages.

I have my {% hook seo %} in my global template working properly however I'm not sure what's wrong with my custom field on unique pages. I have tried the following in a unique page:

`{% set seo = craft.seo.custom('my title','my description') %}`

It eventually returns the name of the website as the title, which confirms that my hook is working but that the custom field is not overwriting it. However, even when I comment out the hook seo from the global template, the custom field doesn't seem to work, at least it doesn't set the title or description.

I guess there might be something wrong in my syntax, so I'm calling for help!

**Comment by Tam** [comment]
It's hard to tell what's wrong without seeing how your templates are set up, but something like this should work:

**_layout.twig**
```twig
<html>
  <head>
    {% hook 'seo' %}
    {# ... head markup ... #}
  </head>
  <body>
    {# ... body markup ... #}
  </body>
</html>
```

**unique-page.twig**
```twig
{% extends '_layout.twig' %}
{% set seo = craft.seo.custom('My Title', 'My description') %}
```

**Comment by NicolasBarse** [comment]
Hey Tam thanks a lot for your help, the issue appeared to be that my custom seo was placed inside the {% block content %} and needed to be placed right after the {% extends '_layout.html' %}, hope this will help someone in the future.
