### ISSUE TITLE
Don't update SEO titles after update

### ISSUE THREAD

**Issue by rinusvandam** [ethercreative/seo#183]
### Description

I'm running a Craft site with 400+ entries. Most of the entries having custom SEO titles defined. When we update Craft and the SEO plugin all SEO titles are set to {title} – {{ siteName }}. Is there anyway to leave the titles as they are set? 

### Steps to reproduce

1. Update Craft to 3.1.5
2. Update SEO to 3.5.3
3. All custom SEO titles are overwritten to {title} – {{ siteName }}

### Additional info

- Craft version: Craft Pro 3.1.5
- SEO version: 3.5.3
- PHP version: 7.3.0
- Database driver & version: MySQL 5.7.23

**Comment by Tam** [comment]
Do the new titles contain any of the previous titles (i.e. `[previous title] - [siteName]`), or are they being completely overwritten? Could you send me screenshots of before and after the upgrade for an entry where the title is being overwritten?

**Comment by rinusvandam** [comment]
They are completely overwritten to {title} – {{ siteName }}.

(Images removed)

**Comment by Tam** [comment]
I've just pushed an update that should allow you to upgrade without losing your existing titles.

**Comment by rinusvandam** [comment]
That was fast! I can confirm this issues is solved. Thanks!
