### ISSUE TITLE
Getting SEO data through CraftQL fails

### ISSUE THREAD

**Issue by roelvanhintum** [ethercreative/seo#187]
### Description
```
String cannot represent non scalar value: instance of Twig_Markup
```

### Steps to reproduce

1. Query with CraftQL
```
query {
  entry(section: [home]) {
    title
    ... on Home {
      seo {
        title
      }
    }
  }
}

```

### Additional info

- Craft version: 3.1.8
- SEO version: 3.5.4
- PHP version: 7.2.8
- Database driver & version: MySQL 5.7.22
- Other Plugins: CraftQL 1.3.1

**Comment by emilioybarra** [comment]
I have the same exact issue unfortunately.

Craft version: Craft Solo 3.1.26
SEO version: 3.5.4
PHP version: 7.2.10
Database driver & version: MySQL 5.5.5
CraftQL version: 1.3.2

**Comment by paco-leyva** [comment]
I have the same issue :(

Craft version: Craft CMS 3.1.29
SEO version: 3.5.4
PHP version: 7.2.17
Database driver & version: MySQL 5.7.25
CraftQL version: 1.3.2

**Comment by jesuismaxime** [comment]
Is there a working exemple of how to use on a channel section ?
