### ISSUE TITLE
SEO: Failed to retrieve entry preview

### ISSUE THREAD

**Issue by makereadyisaac** [ethercreative/seo#193]
### Description

We just pushed a site from dev to production, and accordingly the url changed from a *.preview domain to the client's domain. After this happened, every entry with the SEO field and focus keywords entered gives the "Failed to retrieve entry preview" error. The live preview pane works just fine, but SEO can't seem to grab any content from it and compare to the keywords for relevancy. I've tried reinstalling and clearing caches and whatnot. I've updated all the site settings to the new domain, purchased a Craft Pro license, etc. This happens on every entry with focus keywords added. If they're removed, the error stops.

### Steps to reproduce

1. Move site from dev to production
2. Add focus keywords to SEO field to check for relevancy
![untitled](https://user-images.githubusercontent.com/40444832/52722012-72c70900-2f70-11e9-8af8-a03faa3a45d4.png)

### Additional info

- Craft version: Craft Pro 3.1.9.1
- SEO version: 3.5.4
- PHP version: 7.2.14
- Database driver & version: MySQL 5.7.25
- Other Plugins: Contact Form / Honeypot, Expanded Singles, Field Manager, Imager, Redactor

**Comment by m-meintjes** [comment]
We have the same issue. Just went live with a new site a few minutes ago. The error appears only on the production environment but not the dev environment.

- Craft version: 3.1.23
- SEO version: 3.5.4
- PHP version: 7.1.16
- Database driver & version: 5.5.62

**Comment by alexjcollins** [comment]
Hey @m-meintjes are there any entries in your logs that relate to this that you can see?

**Comment by m-meintjes** [comment]
> Hey @m-meintjes are there any entries in your logs that relate to this that you can see?

Hey @alexjcollins thanks for your reply. We figured it out. There was a cross-site exception because the domain int the .env file did not have www. in front of the domain. Everything works fine now.

**Comment by makereadyisaac** [comment]
Solved it for us too. Client had set their DNS to make www. the canonical url, but I'd set it without the www. in Craft. Setting it to www. solved it. Thanks all!
