### ISSUE TITLE
Don't include siteName on home page

### ISSUE THREAD

**Issue by tyssen** [ethercreative/seo#194]
### Description

For a site I'm working on, the home page requires a custom title that's not made up of entryTitle – siteName.

In the settings, I've unlocked siteName and when I edit the entry, I remove the site name value which is automatically entered, but when I save, it's still being output, and when I go to edit the entry again, the field is filled in.

### Additional info

- Craft version: 3.1.8
- SEO version: 3.5.4
- PHP version: 7.1
- Database driver & version:
- Other Plugins:

**Comment by bertoost** [comment]
This is really necessary! It should be possible to override this via the custom SEO tag

**Comment by alexjcollins** [comment]
@bertoost we're discussing internally. For now, you can create a separate SEO field for the homepage that is configured differently

**Comment by ugrupp** [comment]
I've managed to work around this by using the entry/element ID. In my case, the homepage had the ID `2`, which likely won't change in the future. So this worked:

`{% if object.id != 2 %} - {{ siteName }}{% endif %}`

**Comment by Tam** [comment]
If you want a different title format for a specific entry type you should create a new SEO field for that type.
