### ISSUE TITLE
UI is almost unusable when focus keywords are filled in

### ISSUE THREAD

**Issue by timbertens** [ethercreative/seo#197]
### Description
The UI in the control panel for managing an individual entry becomes almost non-responding when focus keywords are filled in. CPU of browser session goes to almost 100% both on Chrome and Safari and the response takes +30 seconds to be returned to the end users.  When no focus keywords are filled in there is no issue

### Steps to reproduce

1. Fill in one or multiple focus keywords

### Additional info

- Craft version: 3.1.16 Solo
- SEO version: 3.5.4
- PHP version:7.2.15
- Database driver & version:MySQL 5.7.25
- Other Plugins:

Craft Cheat Sheet  2.0.3
Embedded Assets 2.0.0
Iconpicker 1.0.5
Migration Manager 3.0.21
Position Fieldtype 1.0.14
Redactor 2.3.2
Static Translations 1.2.0
Video Embedder 1.1.1
Wheel Form 1.23.0

**Comment by alexjcollins** [comment]
Hey @timbertens thanks for brining this to our attention. We'll dig into this an get back to you as soon as we can

**Comment by carolineboeykens** [comment]
@alexjcollins, do you have an update on this issue? We are having trouble with this too.

Versions:
Craft CMS: 3.3.3
SEO: 3.6.2

**Comment by Tam** [comment]
@carolineboeykens Are you using any of the same plugins as @timbertens?

**Comment by carolineboeykens** [comment]
Yes, we are also using: 

Position Fieldtype 1.0.14
Redactor 2.4.0
Video Embedder 1.1.4

**Comment by Tam** [comment]
@timbertens @carolineboeykens Can you send a database dump to dev@ethercreative.co.uk?
