### ISSUE TITLE
&amp; appears as &amp; instead of & in social media preview

### ISSUE THREAD

**Issue by joshcoast** [ethercreative/seo#198]
### Description
If we use an `&` in a site title, `&amp;` appears as `&amp;` instead of `&` in social media preview. Not a huge deal, but takes some explaining to clients. 

### Steps to reproduce
1. Have a site name with an & in it. 
2. Craft (I'm guessing) will translate this into the HTML `&amp;`. 
3. The social media preview doesn't translate it back to `&`.

### Additional info
![image](https://user-images.githubusercontent.com/1174626/54088623-9f7b0000-4325-11e9-95ea-c501f6e26d08.png)
Great Plugin BTW! Keep up the great work 🥇 

- Craft version: Craft Pro 3.1.16
- SEO version: 3.5.4
- PHP version: 7.2.6
- Database driver & version: MySQL 5.6.40
- Other Plugins: 
Control Panel CSS
Elastic Search
Migration Manager
Query
Queue Manager
Redactor
SEO
Sidebar Themes
SimpleMap
Sprout Email
Sprout Fields
Sprout Forms
SuperSort
Super Table
Wordsmith

**Comment by janhenckens** [comment]
Also running into this.

**Comment by jasonlav** [comment]
Experiencing issue as well. Specifically in the website titles and single quotes.

PHP 7.2.14
SEO 3.5.4
Craft Craft Pro 3.1.23

**Comment by sctgraham** [comment]
Similar case for me with page titles and also FB and Twitter social media title tags.
In my case it's just apostrophes (') that are rendered as `&#39;` but all other characters are OK, which is weird. 

PHP 7.1.6
Craft Pro 3.1.25
SEO 3.5.4

A work around would be much appreciated if anyone has one, pending an official fix.

**Comment by sctgraham** [comment]
Any news on this ? A fix or a workaround would be great, anyone ? Thx

**Comment by janhenckens** [comment]
Still having issues with this on a couple of sites. Any updates here?

**Comment by mattnemoz** [comment]
Hello ! 
I'm happy to see that i'm not the only one who have this problem too ! :-)
If you please have a solution for theses apostrophes who apears in `&#0039;` it would be great !

**Comment by sctgraham** [comment]
Hi, any news on this ? 
This is a great plugin, but this issue has become quite a stumbling block for me. The website I’m administrating is in French and every other title has an apostrophe which gets outputted as `&#39;`.
Thanks !!

**Comment by ArtDepartmentMJ** [comment]
Still having this issue on titles with apostrophes
