### ISSUE TITLE
Error on settings: Trying to get property of non-object

### ISSUE THREAD

**Issue by rickprince** [ethercreative/seo#2]
Error when I try to access /admin/seo/settings, I get the following error
![](http://share.ply.digital/r/ncDXJaMF.png)

Running latest version of craft under php 7. Dashboard, Sitemap & Redirects areas don't have this issue. Any ideas?

**Comment by Tam** [comment]
Could you let me know what other fields you have, and any other plugins you are running?

**Comment by rickprince** [comment]
Fieldtypes:
![](http://share.ply.digital/r/5YM4iyEK.png)

I have also disabled every other plugin and updated craft to 2.6.2780 but no luck...

**Comment by Tam** [comment]
I haven't been able to replicate the bug, but I've pushed a possible fix to the main repo that should solve the problem. Would you be able to pull/[download](https://github.com/ethercreative/seo/archive/master.zip) and test it?

**Comment by rickprince** [comment]
Well, it's a different error this time so that's progress, right?

`Fatal error: Call to a member function getName() on a non-object in /craft/plugins/seo/controllers/SeoController.php on line 119
`
I can provide a copy of the site if you'd like to take a look for yourself?

**Comment by Tam** [comment]
I've pushed another fix for you to try! 
If this doesn't work then if you could provide a copy of your site for me to debug I should be able to work out a full fix.
