### ISSUE TITLE
Issue with canonical URLs with SEO

### ISSUE THREAD

**Issue by ErwinHolygrow** [ethercreative/seo#202]
It looks like the canonical url is set twice on every page. One of these canonical links does not seem to work, linking to "https://example.com/<https://example.com/>"

It looks like the issue occurs in these lines inside the SeoService.php:
`public function injectCanonical ()
{
	list($field) = $this->_getElementAndSeoFields();
	\Craft::$app->getResponse()->getHeaders()->add(
		'Link',
		'<' . $field->canonical . '>; rel="canonical"'
	);
}`

Is there any reason for a http header being set with a canonical aswell as a link tag?

- Craft version: 3.1.16
- SEO version: 3.5.4 
- PHP version: 7.2.4

Thanks in advance

**Comment by everythingdigital** [comment]
I have this problem too, my links seen "https://www.seoium.com/ https://www.seoium.com/"
