### ISSUE TITLE
Redirect precendence

### ISSUE THREAD

**Issue by paragonn** [ethercreative/seo#203]
### Description
We have a number of redirects that follow this pattern /give/123456 
Where 123456 is a random 6 character number. 
However we have one catch all redirect like so: give/([0-9]{6})(.*)
We have added the catch all as the last redirect, unfortunately on a good number of the redirects it takes precedence over the more specific redirects setup before it.

### Steps to reproduce

1. Create a few redirects like so give/123456(.*) (obviously the 123456 number would be replaced with the specific id you're trying to redirect)
2. Create a catch all redirect give/([0-9]{6})(.*)

### Additional info

- Craft version:
- SEO version:
- PHP version:
- Database driver & version:
- Other Plugins:

**Comment by rolfkokkeler** [comment]
same issue here

Additional info
Craft version: 3.1.28
SEO version: 3.5.4
PHP version: 7.2.28
Database driver & version:  MySQL 5.5.5

**Comment by Tam** [comment]
I've added a feature request for this, see #274.
