### ISSUE TITLE
Notice: Undefined property: Craft\Exception::$statusCode in /Users/tam/Sites/claas/craft/plugins/seo/SeoPlugin.php on line 123

### ISSUE THREAD

**Issue by Tam** [ethercreative/seo#21]
`Notice: Undefined property: Craft\Exception::$statusCode in /Users/tam/Sites/claas/craft/plugins/seo/SeoPlugin.php on line 123`

**Comment by PetterRuud** [comment]
if(property_exists($event->exception, 'statusCode') && $event->exception->statusCode)

**Comment by Tam** [comment]
Fixed in v1.3.0
