### ISSUE TITLE
seo.title is not refreshed in existing entries or new entries

### ISSUE THREAD

**Issue by timbertens** [ethercreative/seo#210]
### Description
What is expected?
* Change the 'Page Title' settings in SEO > Settings > FieldType > Page Meta > Page Title (eg. adding a token or string)
* Hit save, then the existing or new entries should get this title format in the SEO field and when outputting the entry

What is actually happening?
* The SEO field in the entries (both for existing and new entries) keep the format as before the change

### Additional info

- Craft version: Craft Solo 3.1.25
- SEO version: 3.5.4
- PHP version: 7.3.1
- Database driver & version: mySQL 5.7.25
- Other Plugins:

CP Field Inspect	1.0.5
Embedded Assets	2.0.3
Field Manager	2.0.5
Iconpicker	1.0.5
Matrix Toolbar	1.0.6
Migration Manager	3.0.21
Position Fieldtype	1.0.14
Redactor	2.3.3.2
SEO	3.5.4
Site Switcher	2.1.0
Static Translations	1.2.0
Table Maker	2.0.1
Typed link field	1.0.19
Video Embedder	1.1.1
Wheel Form	1.25.3

**Comment by daniellelecomte** [comment]
Having this same issue on Craft 3.1.24.

**Comment by janvl** [comment]
Same issue on Craft 3.1.21

**Comment by mightyfineyall** [comment]
Same issue here, Craft 3.1.30

**Comment by GeorgosXL** [comment]
Experiencing the same issue in Craft 3.1.30 :)
Does someone have a work around solution for this, until this is fixed? 
Cheers

**Comment by Tam** [comment]
The Page Meta settings under SEO > Settings only affect new SEO fields or templates that use `craft.seo.custom()`. To update the title structure for entries you'll want to update field that those entries use.

I've updated the instructions explain this better in the next release.
