### ISSUE TITLE
Multiple SEO fields taking social titles from last on page.

### ISSUE THREAD

**Issue by billythekid** [ethercreative/seo#212]
### Description

I have a matrix field in which each block has an SEO field. When updating the social title on any following field it takes the social title from the last. Seems like the JS targeting this should be more specific perhaps?

### Steps to reproduce

1. Click on a social title in the second SEO field (second matrix block's SEO field, where there are at least 3 matrix blocks with this filled in)
2. Observe it take the SEO title from the last one via JS.

### Additional info

- Craft version: 3.1.24
- SEO version: 3.5.4
- PHP version: 7.3
- Database driver & version: MySQL 5.7.26
--

- Other Plugins:

**Comment by Tam** [comment]
SEO only supports one field per-entry

**Comment by billythekid** [comment]
This isn't in an entry. It's in a global matrix for use where we don't have entries or categories or whatever but still want to use the seo field on the rendered page.
