### ISSUE TITLE
Redirect not working from index.php?page=  

### ISSUE THREAD

**Issue by drivebrand** [ethercreative/seo#214]
### Description
I'm trying to add the following redirect and instead of going to /the-code it goes to the homepage. I've tried adding some other redirects and they work as expected, it only seems to be an issue with index.php.

index.php?page=planning-your-hike the-code 302

### Additional info

- Craft version: 3.1.28
- SEO version: 3.5.4

**Comment by alexjcollins** [comment]
Have you tried adding a / at the start of the request uri?

**Comment by drivebrand** [comment]
It doesn't seem to make a difference with or without the slash.

![image](https://user-images.githubusercontent.com/12936683/58491894-d7802b00-813d-11e9-9222-c250a4d1236c.png)

**Comment by alexjcollins** [comment]
@Tam Are you able to weigh in on this one?

**Comment by drivebrand** [comment]
I'm guessing it has something to do with this line in .htaccess.  Wondering if I will need to make changes directly in the htaccess file rather than in SEO?
    RewriteRule (.+) index.php?p=$1 [QSA,L]

**Comment by Tam** [comment]
@drivebrandstudio You don't need to include `index.php?p=` in your redirects. `planning-your-hike` is all you need.

**Comment by laurabennett** [comment]
Running into this again with another site. Never got addressed in the original site either.
https://hikesafe.com/index.php?page=planning-your-hike%20the-code
https://www.whitemountainhealth.org/index.php?page=become-a-patient
