### ISSUE TITLE
Optimisation Checklist says that the word does not appear in the first paragraph when it does.

### ISSUE THREAD

**Issue by brycekirk** [ethercreative/seo#216]
### Description
Optimisation Checklist says that the word does not appear in the first paragraph when it does.

### Steps to reproduce

1. Add a keyword to Focus Keyword
2. Write the first paragraph with the focus keyword in it
<img width="680" alt="Screen Shot 2019-06-06 at 9 54 19 AM" src="https://user-images.githubusercontent.com/18602341/59047882-fec3b000-8841-11e9-9759-e58076ccf20c.png">
<img width="667" alt="Screen Shot 2019-06-06 at 9 54 10 AM" src="https://user-images.githubusercontent.com/18602341/59047893-01bea080-8842-11e9-87da-0735639035e3.png">

### Additional info

- Craft version: Craft Solo 3.1.29
- SEO version: 3.5.4
- PHP version: 7.3.1
- Database driver & version: MySQL 5.7.25
- Other Plugins: Feed Me, Redactor, Redactor Custom Styles, Simple Sharing, Wheel Form

**Comment by alexjcollins** [comment]
Is that content in the first `<p>` on the page when viewing your template/src?

**Comment by brycekirk** [comment]
No... I have a contact overlay and a mega menu that contain `<p>` tags. Is it possible to change where the plugin looks? ie check in `article p` instead?

**Comment by alexjcollins** [comment]
I think that would be a nice feature and certainly something we'll consider in the next update.

Google will more than likely skip over the overlay and menu `<p>`'s and go straight in to your content, but I get it's annoying seeing that it's not 'done', especially if a client is accessing and reviewing that information.

I'll leave this up here and we'll address in the (hopefully!) near future.

**Comment by brycekirk** [comment]
Yes, the other `<p>`'s are in `<nav>` tags, so it shouldn't present a problem.

Thanks, this feature would be much appreciated! In the meantime, is it possible to edit a core file to get this to work?
