### ISSUE TITLE
Optimization checklist incorrectly reading image alt tags

### ISSUE THREAD

**Issue by brycekirk** [ethercreative/seo#217]
### Description
The Optimization checklist says less than half images have alt tags containing the keyword when they all do

### Steps to reproduce

1. Add a focus keyword
2. Make a couple images, edit them and add the keyword into the Title input
![Screen Shot 2019-06-06 at 10 13 47 AM](https://user-images.githubusercontent.com/18602341/59048794-dd63c380-8843-11e9-997d-27ec148021aa.png)
<img width="728" alt="Screen Shot 2019-06-06 at 10 09 01 AM" src="https://user-images.githubusercontent.com/18602341/59048801-e05eb400-8843-11e9-9d89-d46a6b441500.png">
<img src="https://user-images.githubusercontent.com/18602341/59048905-14d27000-8844-11e9-9d2d-bc042b468023.jpg" />

### Additional info

- Craft version: Craft Solo 3.1.29
- SEO version: 3.5.4
- PHP version: 7.3.1
- Database driver & version: MySQL 5.7.25
- Other Plugins: Feed Me, Redactor, Redactor Custom Styles, Simple Sharing, Wheel Form

**Comment by alexjcollins** [comment]
Hmm, I wonder if this is case related. If you add `Podcast` as a focus keyword does that work? If so that should hopefully be a relatively simple fix.

**Comment by brycekirk** [comment]
Yeah, I think the reason is that there are a bunch of other images on the webpage (logo, page images in the mega menu, author image) that I'm guessing count towards the total. So all added up, less than half the images have "Podcast" in the alt tag.

I would definitely love a feature to specify an element / id / class that contains the blog content so that these checks work on sites like the one I'm working on :)
