### ISSUE TITLE
Cant access seo variable inside Twig?

### ISSUE THREAD

**Issue by nexflo** [ethercreative/seo#22]
Hey,

inside the twig templates the seo fields are always returning empty..and not the text and description added to the plugin?

Thanks

Flo

**Comment by Tam** [comment]
Are the fields saving correctly? Also, could you let me know what version of Craft & the plugin you are using, any other plugins you have installed, and the template code you are using.

**Comment by robi-bobi** [comment]
I might be having the same issue.

Fields are populated if I reopen the page in Admin, so they must be saving OK.
However when in twig, I always get into:
`seo is not defined` part

Beside adding SEO field is there anything else that I should do in order for `seo` to be defined?

**Comment by Tam** [comment]
@robi-bobi It sounds like you're not setting the `seo` variable. If you're using the snippet from the docs, try changing:

```twig
{% if seo is not defined %}
    {% set seo = craft.seo.custom(siteName, '', false) %}
{% endif %}
```

to

```twig
{% if seo is not defined and entry.seo is defined %}
	{% set seo = entry.seo %}
{% endif %}
{% if seo is not defined %}
	{% set seo = craft.seo.custom(siteName, '', false) %}
{% endif %}
```

From the docs:
> The code snippet above assumes that you will be creating a variable call seo in your templates that will return either the SEO field or a custom SEO object (see below).

You need to set the `seo` variable. In the example above, we're setting it to whatever the current `entry`'s `seo` field is.

**Comment by robi-bobi** [comment]
Thank you, that was it.
