### ISSUE TITLE
SEO: Failed to retrieve entry preview

### ISSUE THREAD

**Issue by brycekirk** [ethercreative/seo#224]
### Description
Three "SEO: Failed to retrieve entry preview" errors are generated as soon as I add a focus keyword. This occurs in all environments.

### Steps to reproduce

1. Make a new entry that has the SEO field
2. Add a focus keyword. 3 errors are generated
3. The same error is generated each time the entry saves or loads

### Additional info

- Craft version: 3.2.2 Pro
- SEO version: 3.5.4
- PHP version: 7.2.19
- Database driver & version: MySQL 5.6.44
- Other Plugins: Cookie Consent Banner, Redactor, Redactor Custom Styles, Simple Sharing, Wheel Form

**Comment by vaughn-taylor** [comment]
I'm seeing this same error using Craft 3.2.5.1 and SEO 3.5.4. While adding content to an entry, the error message "SEO:  Failed to retrieve entry preview" is constantly showing at the top of the screen.

This is the full chain from console:

SEO:  Failed to retrieve entry preview
l @ fail.js:4
Promise.then (async)
u @ Tabs.js:66
d @ EntryMarkup.js:39
Promise.then (async)
u @ Tabs.js:66
d @ EntryMarkup.js:39
(anonymous) @ EntryMarkup.js:39
(anonymous) @ EntryMarkup.js:39
(anonymous) @ EntryMarkup.js:39
value @ EntryMarkup.js:39
value @ KeywordChecklist.js:53
(anonymous) @ FocusKeywords.js:178
value @ FocusKeywords.js:160
value @ FocusKeywords.js:82
e @ FocusKeywords.js:39
e @ SeoField.js:56
(anonymous) @ 165-how-to-use-imager-with-imagemagick-to-get-cool-effects:1189
e @ jquery.js:3557
t @ jquery.js:3625
setTimeout (async)
(anonymous) @ jquery.js:3663
n @ jquery.js:3291
fireWith @ jquery.js:3421
fire @ jquery.js:3429
n @ jquery.js:3291
fireWith @ jquery.js:3421
ready @ jquery.js:3901
B @ jquery.js:3911

**Comment by mattobee** [comment]
I'm seeing the same after upgrading to Craft 3.2.5.1 and SEO 3.5.4.

**Comment by codeartaus** [comment]
Same issue here

**Comment by rauwebieten** [comment]
We have the same issue in version 3.6.6 (craft v 3.4.30)

```
SEO:  Failed to retrieve entry preview fail.js:4:33
    r fail.js:4
    update SeoField.min.js:1
    update SeoField.min.js:1
    calculate SeoField.min.js:1
    b SeoField.min.js:1
    setActiveKeyword SeoField.min.js:1
    initKeywords SeoField.min.js:1
    b SeoField.min.js:1
    <anoniem> SeoField.min.js:1
```

**Comment by forcehobbit** [comment]
We have also the same issue in version 3.6.6 (craft v 3.4.27)

Actually I found that the error occurs, if on the target page, no svg image is available. Javascript fails on `forEach`, because the Regex does not match, if no svg is available.
