### ISSUE TITLE
SEO Title isn't updating in Craft 3.2

### ISSUE THREAD

**Issue by carolineboeykens** [ethercreative/seo#225]
### Description
When we change the title of the entry the SEO title changes. But when we 'update entry' the SEO title is set again to the previous title. When we change the SEO title manually it works.

### Steps to reproduce

1. Create an entry with a title.
2. Save entry
3. Rename the entry and update the entry
4. The SEO title did not update

### Additional info

- Craft version: 3.2.2
- SEO version: 3.5.4

**Comment by Tam** [comment]
This should be fixed in the latest release.

**Comment by carolineboeykens** [comment]
This bug is happening again in Craft version: 3.3.7.
SEO version: 3.6.2

Can you take a look at it again?
