### ISSUE TITLE
Keywords cannot be added with enter

### ISSUE THREAD

**Issue by chukura** [ethercreative/seo#231]
### Description
Keywords cannot be added to entries. Hitting "enter" as instructed saves the entry and reloads the page.

### Steps to reproduce

1. Type keyword into field
2. Hit enter (as instructed)

### Additional info

- Craft version: 3.2.8
- SEO version: 3.6.1.1
- PHP version: 7.2.8
- Database driver & version: MySQL 5.7.23

**Comment by Tam** [comment]
@kojint Is this still an issue, I can't re-create it. What browser are you using?

**Comment by alexhillel** [comment]
I'm seeing this with Chrome 75 on macOS.

**Comment by alexhillel** [comment]
Actually, 3.6.2 appears to solve this.

**Comment by chukura** [comment]
I can confirm that 3.6.2 seems to solve this.
