### ISSUE TITLE
SEO title can not be changed

### ISSUE THREAD

**Issue by janhenckens** [ethercreative/seo#233]
### Description
This is the same issue as #225, where we change the seo title, save the entry but the changes are not being saved.

### Steps to reproduce

1. Change the seo title
2. Save the entry
3. The title you entered in step 1 is not the title you see now

### Additional info

- Craft version: 3.2.8
- SEO version: 3.6.11
- PHP version: 7.2.11
- Database driver & version: 5.7

**Comment by rolfkokkeler** [comment]
same issue here

**Comment by coenfuze** [comment]
I'm having this issue as well. And the problem is somewhere in SeoField.js `Uncaught TypeError: Cannot read property 'parentNode' of null`. A "hotfix" for now is altering the DOM using devTools and set the value manually of the input below the `seo--snippet-title-editable` span.
