### ISSUE TITLE
SEO title always includes siteName

### ISSUE THREAD

**Issue by coenfuze** [ethercreative/seo#234]
I'm currently working on a multi-language Craft project where we are using this plugin to render the title tags. But there seems to be a limitation/problem which prevents editing the actual site name which is concatenated after the seoTitle.

For example this Craft setup;

**Settings -> Sites**
```
AwesomeSite EN
AwesomeSite NL
```

In this case I would like to have AwesomeSite (just the systemName) without it's internal references (EN, NL) in the title, but SEO will always render:

```
Custom SEO Title - AwesomeSite EN 
Custom SEO Title - AwesomeSite NL
```

The only way I managed to handle this is by using the follow structure:

Under SEO-settings i removed all tokens and added a "null" token. After that I included a custom SEO template using **titleRaw** to get the actual titel whithout the siteName

```
{% set seo = getSeoField() %}
{% if seo is null or seo.title == '' %}
    {% set seo = craft.seo.custom(systemName, '', false) %}
{% else -%}
    {% set seo = craft.seo.custom((seo.titleRaw ? seo.titleRaw[1] : entry.title) ~ ' - ' ~ systemName, '', false) %}
{% endif %}

<title>{{ seo.titleRaw != null ? seo.titleRaw[0] : seo.title }}</title>
```

Shouldn't there be an easier way to accomplish this? Thanks.

**Comment by Tam** [comment]
@qorridor I'd recommend adding a token to the SEO field that contains the hard-coded system name, rather than `{siteTitle}`.
