### ISSUE TITLE
SEO preview shows wrong url for site

### ISSUE THREAD

**Issue by janhenckens** [ethercreative/seo#237]
### Description
In an install with 2 sites, the SEO field's preview for entries in site B shows the url for site A (site A is also the primary site in this case)

### Additional info

- Craft version: 3.2.9
- SEO version: 3.6.2
- PHP version: 7.2.1

**Comment by bertoost** [comment]
Additional to this;
It doesn't show the full URL of the current entry. Like when it's in a structure, 4th level, then it only shows `{{ siteUrl }}` (which is indeed the URL of the CP on that moment) and the current entry slug, not the URI.
Better is to use `$entry->getUrl()` for this and not doing fancy stuff like replacing the siteUrl etc.
I will try to make a PR for this.

[edit]
Hmm, some other test project does show the correct url. Weird
