### ISSUE TITLE
[FR] Change SEO Meta Template from single-line input to textarea AND/OR allow to define the template somewhere in code.

### ISSUE THREAD

**Issue by ClemensSchneider** [ethercreative/seo#238]
Having the whole template in one line is not easy to read, so it would be nice to have a text-area here.

Even better would be the ability to define the Seo Meta Template somewhere in the codebase so it can be put into source control.

**Comment by alexjcollins** [comment]
@ClemensSchneider You can reference a file in that field - it's not actually designed for pasting anything else.

So for example, if you had a file in your templates directory called `_seo.twig` that had all your meta, you would just add `_seo.twig` in the SEO Meta Template field.

**Comment by ClemensSchneider** [comment]
:D nice... Thanks for the hint and sorry for the noise!
