### ISSUE TITLE
Direct link to images without transform?

### ISSUE THREAD

**Issue by MrGlasspoole** [ethercreative/seo#240]
For Twitter and FB i already have the right image on the server.
So there is no need to transform.
So instead of:
```https://mydomain.net/index.php?p=actions/assets/generate-transform&transformId=1```
It should be:
```https://mydomain.net/media/mypicture.png```

Is there a reason for making the FB image 1200 x 600?
The recommendation is: 1200 x 628 / 1.91:1

**Comment by alexjcollins** [comment]
@MrGlasspoole 

**For Twitter and FB i already have the right image on the server.**
It's great that it is the case for you, but some individuals will want to be able to upload any image and have the CMS transform it for them.

Regarding the size, thanks for bringing to our attention. A fix has been pushed https://github.com/ethercreative/seo/commit/78076d61c30b0b70f95b1527934c0554b47d3834 and will be released soon.

**Comment by MrGlasspoole** [comment]
I'm not saying it should be for anybody. I'm asking if its maybe possible to do it in the custom template or some other way.

Twitter image card (Twitter shared link) should also be 1200 x 628 now:
https://louisem.com/217438/twitter-image-size
