### ISSUE TITLE
Query string not working in redirect

### ISSUE THREAD

**Issue by benrnorman** [ethercreative/seo#242]
### Description
Redirects from URLs with query strings 404. I would except the redirect to work successfully and preserve the query string by default.

I believe it is related to https://github.com/ethercreative/seo/issues/70

### Steps to reproduce

1. Add redirect from **contact-us** to **contact**
2. In browser, visit **contact-us**. It successfully redirects to **contact**
3. In browser, visit **contact-us?example=query**. It fails with 404

### Additional info

- Craft version: 3.2.10
- SEO version: 3.6.2
- PHP version: 7.0.33-1~dotdeb+8.1
- Database driver & version: mysql 5.5.62
- Other Plugins: Redactor 2.3.3.2, CP Field Inspect (1.0.6)

**Comment by benrnorman** [comment]
I don't know if this would have knock-on effects with other redirects that use the regex matching, but for my purposes I got it working by modifying the "findRedirectByPath" function in RedirectsService.php like so:

**OLD**
```
public function findRedirectByPath ($path)
{
	$redirects = $this->findAllRedirects(true);

	foreach ($redirects as $redirect)
	{
		$to = false;

		if (trim($redirect['uri'], '/') == $path)
			$to = $redirect['to'];

		elseif ($uri = $this->_isRedirectRegex($redirect['uri']))
			if (preg_match($uri, $path))
				$to = preg_replace($uri, $redirect['to'], $path);

		if ($to)
		{
			return [
				'to' => strpos($to, '://') !== false
					? $to
					: UrlHelper::siteUrl($to),
				'type' => $redirect['type'],
			];
		}
	}

	return false;
}
```

**NEW**
```
public function findRedirectByPath ($path)
{
	$qs = preg_split("/\?/", $path);
	$redirects = $this->findAllRedirects(true);

	foreach ($redirects as $redirect)
	{
		$to = false;

		if (trim($redirect['uri'], '/') == $path)
			$to = $redirect['to'];

		elseif (trim($redirect['uri'], '/') == $qs[0] and $qs[1])
			$to = $redirect['to'] . '?' . $qs[1];

		elseif ($uri = $this->_isRedirectRegex($redirect['uri']))
			if (preg_match($uri, $path))
				$to = preg_replace($uri, $redirect['to'], $path);

		if ($to)
		{
			return [
				'to' => strpos($to, '://') !== false
					? $to
					: UrlHelper::siteUrl($to),
				'type' => $redirect['type'],
			];
		}
	}

	return false;
}
```

**Comment by RandomJo** [comment]
I've got the same issue with SEO version 3.6.2 and Craft version 3.3.0.

**Comment by Tam** [comment]
You can use a regex to account for the query string:
```
From: contact-us(.*)
To: contact$1
```
Doing this allows you to have greater control over your redirects, including how you redirect query parameters.

**Comment by RandomJo** [comment]
Leaving this comment for anyone else having this issue in the future. Looking back, I realize that our client was adding slashes at the beginning which is fine when you're not using regex but not so good in combination with regex.

So `/contact-us(.*) `doesn't work but `contact-us(.*)` does.

**Comment by benrnorman** [comment]
Thank you @Tam and @RandomJo, this combo got me over the line!

**Comment by collin-thomasmore** [comment]
Don't think this issue should be closed. 

With the contact-us(.*), you can indeed redirect the query strings. 
But it will also will redirect contact-us/thanks for example because (.*) is a check for all the words after it not only the query strings.

**Comment by jacotijssen** [comment]
@collin-thomasmore ran into the same issue, fixed it by doing this:
```
From: contact-us(\?.*)
To: contact$1
```

**Comment by jordannbeattie** [comment]
I ran into the same issue and found that adding `(\?.*|$)` would resolve the issue. 
```
From: contact-us(\?.*|$)
To: contact$1
```

Adding `(\?.*)` would only be detected if there were parameters but not when there weren't.
