### ISSUE TITLE
URGENT: sitemap.xml producing 404 urls

### ISSUE THREAD

**Issue by jacksutherland** [ethercreative/seo#246]
### Description

One of my sites is producing a valid sitemap.xml however the sitemap xml urls it lists all result in 404's
The url is: https://providenceeye.com/sitemap.xml

Ironically, when I view the sitemap locally or on the dev site, I do not get 404's. It's only on the production environment, despite being an exact replica of my local.

The url for dev is: http://dev.providenceeye.com/sitemap.xml

The only difference is the prod site is https, while dev is http. By chance does this not work over https?

### Steps to reproduce

1. View provided sitemap link.
2. Open one of the sitemap urls produced in it.
3. Experience a 404.

### Additional info

- Craft version: 3.3.01
- SEO version: 3.6.2
- PHP version: 7.0.33
- Database driver & version: MySQL 5.5.60-MariaDB MariaDB Server
- Other Plugins: Redactor, Super Table, Link

**Comment by alexjcollins** [comment]
Hey @jacksutherland sorry for the delay. It looks like you've sorted this (both links work). Is that correct?
