### ISSUE TITLE
Fallback social image is no longer pulled in

### ISSUE THREAD

**Issue by ClemensSchneider** [ethercreative/seo#247]
### Description
The default social image is not used as fallback and it seems that commit https://github.com/ethercreative/seo/commit/7d37adc96cde0a93c9c0ac0db7a168b7b81a9f2b broke it.

Fallback-data contains an `image` field only while `SeoData` has a `imageId` property -> `image` from fallback-data is never pulled in into `SeoData->imageId`.

### Steps to reproduce

1. Assign a default social image
2. Render a page without a social image set

### Additional info

- Craft version: 3.2
- SEO version: 3.6.2
- PHP version: 7.1
- Database driver & version:
- Other Plugins:

**Comment by qbunt** [comment]
also having the same issue here

**Comment by cole007** [comment]
Experiencing the same issue - it looks like the SocialData object is either not returning the fallback image or is in the incorrect format (should be passing an ID rather than the object).

For example:

```
if ((!array_key_exists('imageId', $config) OR empty($config['imageId'])) && array_key_exists('image', $fallback))
  {
    $config['imageId'] = $fallback['image']['id'];
    unset($fallback['image']);
  }
```

**Comment by ryanmasuga** [comment]
Just came upon this issue, too. Using the default SEO template, the Default Social Image is not being pulled in, so I have to manually add an image to every entry.

- Craft version: 3.3.15
- SEO version: 3.6.2
- PHP version: 7.2.22

**Comment by ryanmasuga** [comment]
We have multiple sites that use this plugin. The fallback image doesn't work, and it's not feasible to ask the client to upload images for all their posts now (even if it's the same image over and over). Any thoughts on a fix, or @cole007's code snippet above?

**Comment by improved-software** [comment]
Having the same issue on multiple sites. Hoping a fix can be implemented.
