### ISSUE TITLE
How to set Robot value from twig template

### ISSUE THREAD

**Issue by joshwalsh** [ethercreative/seo#248]
Hello,

I have an entry section that uses the SEO Custom object, but I need to set a noindex robots setting on that entry type.  I can't figure out how to do this.

From what I can tell, the robots values are set via the header, not the meta tag.  Is there a recommended way to force noindex from the template via the plugin?  

I could just force the meta tag into the head outside of the plugin, but thought there may be a more appropriate way to do this through the plugin?

**Comment by Tam** [comment]
You can use Crafts header tag: `{% header "x-robots-tag: none" %}`

**Comment by nordentwickler** [comment]
Info: `{% header "X-Robots-Tag: none" %}` - it should be written like this. If X-Robots-Tag is written with small cases, its getting ignored by chrome.

**Comment by alexjcollins** [comment]
Thanks @nordentwickler 🙌
