### ISSUE TITLE
Wildcard support in redirects

### ISSUE THREAD

**Issue by alexjcollins** [ethercreative/seo#25]
Ability to add carried wildcard support in the redirects i.e

http://example.com/directory/* to http://example.com/new-directory/*

Where anything after the **/directory/** in the source URI is included in the redirect after the **/new-directory/** URI

**Comment by Tam** [comment]
They're already a thing, using .htaccess style regexes. I've updated the README with an example in v1.3.0. I've pasted the example below:

**Redirect Regex Example**
To redirect from `blog/2016/my-post` to `news/my-post` you would add the following redirect:
URI: `blog/([0-9]{4})/(.*)` To: `news/$2`

Useful link: http://mod-rewrite-cheatsheet.com/
