### ISSUE TITLE
Sitemap only returns first 100 URLs for each section

### ISSUE THREAD

**Issue by gazsp** [ethercreative/seo#26]
This severely affects a sites SEO. 

This fix is to add

```
$sect->limit = 9999;
```

to `Seo_SitemapController.php` in `_generateUrls` after `$sect = craft()->elements->getCriteria($elemType);`

**Comment by thijskaspers** [comment]
I would set the limit to `null` to disable it. (Instead of 9999)

**Comment by Tam** [comment]
Fixed in v1.3.0
