### ISSUE TITLE
No sitemap being generated.

### ISSUE THREAD

**Issue by steveDL** [ethercreative/seo#286]
### Description
No sitemap generated even though plugin says sitemap updated upon save. I am looking in the web folder but no sitemap exists, I am assuming this is the place to look. Forgive me if I am missing something but I couldn't find out anything about the specifics of this in the docs I thought it would auto generate but it hasn't.

### Steps to reproduce

1. Fresh install of plugin
2. Selected all sections for sitemap and defined priority etc
3. hit save

### Additional info

- Craft version: Craft Pro:  3.4.5
- SEO version:3.6.3
- PHP version:7.3.7
- Database driver & version: MySQL 5.7.26
- Other Plugins: schema, redactor, contact form, Craft reCAPTCHA 3, tags

**Comment by alexjcollins** [comment]
Hey @SteveQ88 

The sitemap is generated dynamically on request. If you append `/sitemap.xml` to your site URL, do you see it?

**Comment by steveDL** [comment]
Thanks so much for the swift reply! Ahh I had no idea it worked that way great thanks.I do see it but each loc is /sitemap_sections_3_0.xml is that how it should be for google etc? forgive my ignorance here.

**Comment by alexjcollins** [comment]
No worries.

Yeah, we're splitting out each craft section into a separate sitemap using a `<sitemapindex>`. This is mainly as a means to help sites with large numbers of entries across channels to process faster.

It's supported by Google: https://support.google.com/webmasters/answer/75712?hl=en

**Comment by steveDL** [comment]
Thanks a lot for your help Alex. I appreciate that this is for bugs only, legend. ✌🏻👽
