### ISSUE TITLE
The generated sitemap contains 'sitemap_sections_[number]_0.xml' instead of the page url

### ISSUE THREAD

**Issue by alessandrochetta** [ethercreative/seo#293]
I enabled all sections and the generated file looks like this:

<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml"> 
<sitemap>
<loc>https://[domain]/en/sitemap_sections_5_0.xml</loc>
<lastmod>2020-02-07</lastmod>
</sitemap>
<sitemap>
<loc>
https://[domain]/en/sitemap_sections_46_0.xml
</loc>
<lastmod>2019-09-16</lastmod>
</sitemap>
<sitemap>
<loc>
https://[domain]/en/sitemap_sections_11_0.xml
</loc>
<lastmod>2019-11-15</lastmod>
</sitemap>
<sitemap>
<loc>
https://[domain]/en/sitemap_sections_49_0.xml
</loc>
<lastmod>2019-09-16</lastmod>
</sitemap>

Any idea on why this is happening?

### Steps to reproduce

1. Enable all sections.
2. Point browser to domain.com/en/sitemap.xml

### Additional info

- Craft version: 2.8.0.2
- SEO version: 1.4.7
- PHP version: 7.2

**Comment by Tam** [comment]
The sitemap is split into multiple smaller sitemaps to ensure it never grows too big to be slow to load, or have more items than Google accepts. What you're seeing is the index of the other sitemaps. Going to those URLs should show you the actual sitemap listing.
