### ISSUE TITLE
Custom SEO Object Not Working

### ISSUE THREAD

**Issue by idawgik** [ethercreative/seo#297]
### Description
I'm attempting to set custom SEO data on a page on my site that is just loading a template, not an entry, so no SEO Field. I'm using the Custom SEO Object.

In my template I have the following code:

```
{% extends "_layout/_framework" %}
{% set seo = craft.seo.custom(
    'My Title', 
    'My Description'
) %}
```

In my framework template, I have:

`{% hook "seo" %}`

However, no matter what I do, the plugin will not use the title/description that I set. It always just shows my Site Name, followed by my Site Name again. My global settings are:

`{title} | {{ siteName }}`

### Additional info

- Craft version: 3.4.16
- SEO version: 3.6.4
- PHP version: 7.2.24
- Database driver & version: MySQL 5.7.29

**Comment by idawgik** [comment]
Ok, so after a bit of additional playing around, I was able to get this working.

It turns out that the default template here: https://github.com/ethercreative/seo/blob/v3/src/templates/_seo/meta.twig?ts=4 actually overrides any value you assign in your page with the `{% set seo = getSeoField() %}` line.

I had to remove that from the SEO template, and then include it on my page templates with entries. Pages without entries I added the custom line. It's all working there.

Not sure if there's a better way to structure that or not in the defaults. But hopefully that helps someone.

**Comment by RyanRoberts** [comment]
@idawgik This helped me, it was exactly the issue I've been having today. Thanks!

**Comment by lindseybradford** [comment]
I also ran into this. I ended up wrapping my hook at the top tier in a block:

```
{% block seo %}
   {% hook "seo" %}
{% endblock %}
```
(_layouts/default.twig)

Which made it easy to override as needed from the entry templates:

```
{% block seo %}
  {% set seo = craft.seo.custom(
    {
      title: 'Media Coverage '
    }
  ) %}
  {{ parent() }}
{% endblock %}
```
(blog/_entry.twig)

The `{{ parent() }}` function allows you to repeat the parent block, as you'd suspect. [More here](https://twig.symfony.com/doc/2.x/tags/extends.html).

**Comment by laurabennett** [comment]
Running into this same issue with Solspace Calendar because they use event rather than entry.
