### ISSUE TITLE
Empty sitemap generated

### ISSUE THREAD

**Issue by fredrik-sogaard** [ethercreative/seo#299]
### Description
Produced sitemap is this:
```
<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml">
<sitemap>
  <loc>
   https://www.elementsofai.com/sitemap_sections_2_0.xml
  </loc>
<lastmod>2020-03-18T12:21:51+01:00</lastmod>
</sitemap>
<sitemap>
  <loc>
    https://www.elementsofai.com/sitemap_sections_4_0.xml
 </loc>
 <lastmod>2020-03-18T12:21:51+01:00</lastmod>
</sitemap>
<sitemap>
   <loc>
    https://www.elementsofai.com/sitemap_sections_1_0.xml
   </loc>
  <lastmod>2020-03-18T12:21:51+01:00</lastmod>
 </sitemap>
</sitemapindex>
```

### Steps to reproduce
The sections are enabled in the plugin's settings:
https://cl.ly/240f098832e8
I've tried clearing all caches.
I've tried resaving the sections. 
I've tried enabling/disabling the sitemaps and saving.

I think it used to work for this site, and it's stopped working, so it's bit strange.
Any insights?

### Additional info

- Craft version: 3.1.15
- SEO version: 3.5.4
- PHP version: 
- Database driver & version:
- Other Plugins:

**Comment by alexjcollins** [comment]
Hi,

That looks correct – you have three sections enabled in the sitemap settings and there are three sitemap groups showing in your pasted code.

If you go to one of those sitemap groups, for example, [this FAQ one](https://www.elementsofai.com/sitemap_sections_2_0.xml), you can see all the URLs for that section.

For more context, we're using sitemap groups to keep sitemap loading (especially for large sites), more efficient. 

You can [find out more here](https://support.google.com/webmasters/answer/75712?hl=en).
