### ISSUE TITLE
Craft 3.5 breaks JavaScript on every Field Settings page

### ISSUE THREAD

**Issue by kobeaerts** [ethercreative/seo#300]
### Description

A JavaScript errors breaks the JavaScript on every field settings page.

### Steps to reproduce

1. Install the lates Craft version
2. Open a field edit page and check the console

### Error:
Uncaught TypeError: Cannot read property 'content' of null
    at r.initSeoTitle (SeoFieldSettings.js:39)
    at new r (SeoFieldSettings.js:31)
    at HTMLDocument.<anonymous> (30:3610)
    at e (jquery.js:3557)
    at t (jquery.js:3625)

### Additional info

- Craft version: 3.5.x-dev
- SEO version: 3.6.4
- PHP version: 7.4.1
- Database driver & version: MySQL 5.7.28
- Other Plugins: Element API, Feed Me, Field Manager, Google Cloud Storage, Super Table, ...

**Comment by joeRob2468** [comment]
I can confirm this is still an issue on the currently live version of Craft 3.5 (Craft Solo 3.5.15.1). It'd be great to get a fix through soon, can't currently use the plugin properly on a few live sites.

**Comment by gromgull** [comment]
A random guess at the reason is that Craft now rewrites element IDs to include the plugin ID:

![image](https://user-images.githubusercontent.com/178028/100525442-34d8ba80-31c1-11eb-921b-43b0535a6a04.png)

The code does `this.getElementById("seoMetaTitle");` - but that's no longer the ID

**Comment by alexjcollins** [comment]
Thanks for the help here guys and especially @kobeaerts for the PR. We'll get this resolved next week.

**Comment by kobeaerts** [comment]
Hey @alexjcollins, thnx for the mention but I'm just the issue reporter ;)

The PR was made by @bendesilva! Many thnx for it!

**Comment by alexjcollins** [comment]
@kobeaerts Sorry - you're right! Thank you @bendesilva 🙏

**Comment by mrnebbi** [comment]
I'm afraid I've spotted an issue with this fix. One of our clients is running Craft 3.3.20.1, and the latest version of the SEO plugin is throwing an Internal Server Error when trying to edit CMS fields (settings/fields/edit/).

```
Call to undefined method craft\helpers\Html::namespaceId()
 in /vendor/ether/seo/src/fields/SeoField.php
```

Reverting getSettingsHtml to before the #323 changes fixes the issue.

If it helps with replication, the field is inside a Super Table.

<img width="1789" alt="SEO Field" src="https://user-images.githubusercontent.com/708691/107351058-1268f480-6ac2-11eb-9dac-4340656b2b0c.png">
