### ISSUE TITLE
Redirect order error on new install

### ISSUE THREAD

**Issue by cole007** [ethercreative/seo#303]
### Description

The new (as of 3.6.5) order parameter in Redirect Records isn't being installed for new projects.

### Steps to reproduce

1. Set up new project
2. Install plugin via `Composer require`
3. Install in Craft CMS
4. Errors viewing redirect tab in back-end and on 404 pages as `order` column in `seo_redirects` table doesn't exist.

```
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'order' in 'order clause'
The SQL being executed was: SELECT *
FROM `seo_redirects`
ORDER BY `order`
```

### Additional info

- Craft version: 3.4.18
- SEO version: 3.6.5
- PHP version: 7.2.20
- Database driver & version: MySQL 5.7.26
- Other Plugins: Feed Me and Redactor

**Comment by controlnocontrol** [comment]
Issue still exists in 3.7.4?  This is also breaking the 404 pages.

**Comment by controlnocontrol** [comment]
Must have been a migration/update issue; if it still happens to your install, just run this db query to fix:
`ALTER TABLE `seo_redirects` ADD `order` INT NULL DEFAULT NULL AFTER `uid`;`
