### ISSUE TITLE
SEO:  Failed to retrieve entry preview

### ISSUE THREAD

**Issue by jevans1808** [ethercreative/seo#307]
### Description

SEO:  Failed to retrieve entry preview. Because of this error, I believe the 'Focus Keywords' block is not working and displaying incorrect data, e.g. no content on page when there is definitely content on the page.

### Steps to reproduce

1. Navigate to entry
2. Go to SEO tab
3. Error is present on load.
![Screenshot 2020-05-28 at 10 43 18](https://user-images.githubusercontent.com/25665181/83126328-944df480-a0d0-11ea-8e54-2d39e86c8394.png)

### Additional info

- Craft version: 3.4.17.1
- SEO version: 3.6.5.1
- PHP version:
- Database driver & version:
- Other Plugins:

**Comment by tschoffelen** [comment]
That indeed seems unrelated to #288. Instead, this is failing on this line:

https://github.com/tschoffelen/seo/blob/patch-1/resources/js/field/EntryMarkup.js#L124

Are you using Craft in a headless mode without preview URLs set up?

**Comment by jevans1808** [comment]
Preview URLs are set up wherever they're required now, I must have completly missed that. That has fixed the issue, 

Many thanks.
