### ISSUE TITLE
Extensible social sites

### ISSUE THREAD

**Issue by AlexandreCarvalhoDeMelo** [ethercreative/seo#312]
I'd like to somehow extend the plugin and create a Linkedin Social Share
How can i do it?

**Comment by alexjcollins** [comment]
Hi @AlexandreCarvalhoDeMelo 
You shouldn't need to add support separately for LinkedIn since it uses the Facebook `og` tags for the snippet sharing.

You can find out more [here](https://www.linkedin.com/help/linkedin/answer/46687/making-your-website-shareable-on-linkedin?lang=en).

**Comment by AlexandreCarvalhoDeMelo** [comment]
My client needs something else for LinkedinBot
meaning that i have to see if linkedinbot is accessing the page and show a different image from facebook, even thought they use the same tag.

**Comment by alexjcollins** [comment]
In that case, I would recommend adding an asset field to the entry for the LinkedIn image, then create your own [Meta Template](https://github.com/ethercreative/seo/blob/v3/src/templates/_seo/meta.twig) based on the default which includes logic for switching the `og` tag source based on the request.
