### ISSUE TITLE
Getting an error when try to save sitemap config

### ISSUE THREAD

**Issue by webtrend** [ethercreative/seo#33]
I am getting 
`Undefined Index : Id` error when I try to save config file. 

Here is the screenshot of the error with debug mode enabled
https://drive.google.com/file/d/0B1ct9-C-VXpGMjF3SXByWTNSUzA/view?usp=drivesdk

Any ideas on what could be wrong?

**Comment by Tam** [comment]
Fixed in [v1.3.2](https://github.com/ethercreative/seo/releases/tag/v1.3.2)
