### ISSUE TITLE
Incorrect Content-type header for sitemap

### ISSUE THREAD

**Issue by jakepm** [ethercreative/seo#334]
### Description

Sitemap.xml generated by the SEO plugin does not have the correct Content-type header.

### Steps to reproduce

1. Install SEO plugin
2. Add a section
3. Configure sitemap to include section
4. Run the sitemap.xml through an online validator 

### Additional info

- Craft version: Craft Pro 3.5.16
- SEO version: 3.6.7
- PHP version: 7.2.31
- Database driver & version: MySQL 8.0.20
- Other Plugins: Retour

**Comment by alexjcollins** [comment]
I can't recreate this; I've checked a bunch of our production sites and they all validate correctly with a `Content-Type` header of `application/xml`. Do you have an example you can share?

**Comment by jakepm** [comment]
For anybody else who has this issue and find this thread, the cause was actually our server enforcing trailing slashes on URLs. Sitemap was not excluded from this rule, so the sitemap.xml request was being redirected to sitemap.xml/ thus giving an incorrect Content-type header when validating the file.
