### ISSUE TITLE
Disable Sitemap Tool

### ISSUE THREAD

**Issue by redalto** [ethercreative/seo#336]
I want to disable the Sitemap tool within the SEO toolset.  How can I do this?  I see no option under SEO > Settings.

### Additional info
SEO version 3.6.6
Craft CMS version 3.5
PHP version | 7.2

**Comment by alexjcollins** [comment]
There is currently no way to completely disable the sitemap. Will add this as a feature request, though.

**Comment by redalto** [comment]
Can you advise a line of code, or some hack that can at least stop it from publishing via robots.txt so I can manually upload my hand-built sitemap.xml file?

**Comment by alexjcollins** [comment]
It's already possible to edit the robots.txt from the admin. 
In an environment where administrative changes are allowed, head to `/admin/seo/settings#settings-robots` and either remove or update the line to suit.

Then, adding a `sitemap.xml` file to your `web` folder will supersede the plugin generated version.

**Comment by redalto** [comment]
Perfect. That solves my issue then.

**Comment by redalto** [comment]
Perfect. That solves my issue then.
