### ISSUE TITLE
Website not index by google 

### ISSUE THREAD

**Issue by ParamjeetSinghIND** [ethercreative/seo#337]
### Description

I have created google webmaster tool and verify it by copy the code in header section but when i try to index my home page then its not done because its show me 

**Indexing request rejected
During live testing, indexing issues were detected with the URL**

URL is not available to Google
It cannot be indexed. [Learn more](https://support.google.com/webmasters/answer/7440203#blocked_by_robotstxt)

Crawl
Time Jan 12, 2021, 10:13:54 PM
Crawled as Googlebot desktop
Crawl allowed? No: blocked by robots.txt
Page fetch Failed: Blocked by robots.txt
Indexing allowed? N/A

**I also found in my home page by source page 	meta name="robots" content="none, noimageindex" **

Please help me to sort of  this issue

**Comment by alexjcollins** [comment]
Is your environment set to `production` in your `.env` file?

**Comment by ParamjeetSinghIND** [comment]
# The environment Craft is currently running in ("dev", "staging", "production", etc.)
ENVIRONMENT="dev"

can you let me know what need to change here.

**Comment by alexjcollins** [comment]
@paramjeetsingh491 If the site is live and running in a production capacity, I would suggest that you change `ENVIRONMENT="dev"` to read `ENVIRONMENT="production"` in your `.env` file.

If, for whatever reason, you can't do that;

1. in the admin visit SEO → Setting → Robots
2. On line 9, change `Disallow: /` to read `Disallow: /cpresources/`
