### ISSUE TITLE
Section Sitemap has no formatting

### ISSUE THREAD

**Issue by brandondeweese** [ethercreative/seo#338]
### Description

The [main sitemap](https://scalecomputing.com/sitemap.xml) looks fine, but the section sitemap files appear as though they have no formatting. Is this the intent? Example: https://www.scalecomputing.com/sitemap_sections_11_0.xml

### Additional info

- Craft version: Craft Pro 3.5.16
- SEO version: 3.6.7
- PHP version: 7.4.3
- Database driver & version: MySQL 8.0.22
- Other Plugins:

        - Architect: 2.3.3
        - Asset Rev: 6.0.2
        - Bugsnag	2.1.2
        - Cloner	1.2.2
        - Control Panel CSS	2.2.1
        - CP Field Inspect	1.2.3
        - Element API	2.6.0
        - Feed Me	4.3.1
        - Field Manager	2.2.1
        - Freeform	3.9.9
        - Imager	v2.4.0
        - Matrix Toolbar	1.0.6
        - Redactor	2.8.5
        - Relabel	2.0.2
        - SEO	3.6.7
        - Simple Sharing	1.0.8
        - Super Table	2.6.4
        - Typed link field	1.0.24
        - Wordsmith	3.3.0.1

**Comment by alexjcollins** [comment]
I can only assume the formatting issue is the browser struggling with the `<xhtml:` tags for the alternate language URLs. Running the section sitemaps through an XML validator show them as valid. Additionally, Firefox renders the XML ok via the inspector.

It would be worth submitting your sitemap index to Search Console to see if Google has any issues with parsing it.

A curious issue 🤔 

![Screenshot 2021-01-18 at 18 36 07](https://user-images.githubusercontent.com/12031196/104952256-0bb3f980-59bc-11eb-8685-f71c8a97dfde.jpg)

**Comment by brandondeweese** [comment]
Thanks for getting back to me. Hmm..that is strange. Are there any plans to address this? Can it even be addressed? Just wondering, because my client prefers the sitemaps render correctly (in browser) and if it's not addressed or even addressable, I might need to switch plugins.

**Comment by alexjcollins** [comment]
People have reported similar issues [here](https://stackoverflow.com/questions/51923627/xml-sitemap-rendering-as-plain-text) and [here](https://stackoverflow.com/questions/24864254/google-multilingual-sitemap-issue). The SEO plugin is following the instructions set out in the [Google documentation](https://developers.google.com/search/docs/advanced/crawling/localized-versions?hl=en&visit_id=637465950083322487-3644426607&rd=2).

As I understand it, if we update line 472 of `SitemapService.php` to:

```
'http://www.w3.org/TR/xhtml11/xhtml11_schema.html'
```

It may probably render correctly in the browser, but may not validate with Google as the second Stack article suggests. I don't have a multisite env to test with so if you'd like to check, try making the change to the file above on a staging environment.
