### ISSUE TITLE
Title Tag Issue

### ISSUE THREAD

**Issue by ParamjeetSinghIND** [ethercreative/seo#339]
I have used Craft CMS and using SEO plugin. I have set seo setting  and just add token for "{title}" and click on lock. But issue is my website name also shwoing in search result. I dont want to show my website name with my seo title. Can you please help me to showing my title as i have put it on seo field.

**Comment by alexjcollins** [comment]
Can you share a link to your website and provide a screenshot of the SEO field settings?
If you'd rather not share them here, please email help[at]ethercreative.co.uk

**Comment by driesbonte** [comment]
When I update the token in settings it does not effect my title in the cms and in the code.

Entry settings:
<img width="324" alt="Screenshot 2021-02-16 at 08 49 52" src="https://user-images.githubusercontent.com/56576739/108033744-c1627e80-7034-11eb-9593-b64d292957ee.png">

SEO settings:
<img width="477" alt="Screenshot 2021-02-16 at 08 49 34" src="https://user-images.githubusercontent.com/56576739/108033749-c293ab80-7034-11eb-84c4-c99a9674547b.png">

**Comment by alexjcollins** [comment]
@driesbonte Is this the global settings or on your field?

**Comment by driesbonte** [comment]
The bottom image is my plugin settings. Where the second token is set locked and begins with a pipe and the name of the brand. The first image is the seo settings on an entry that doesn't take the settings from the plugin settings.

**Comment by alexjcollins** [comment]
@driesbonte Could you check the settings on the field? It probably needs updating there, too.

**Comment by driesbonte** [comment]
@alexjcollins I only can edit CRM (see example) and not the rest.
I also expect that the global settings is default for all entries.

**Comment by alexjcollins** [comment]
@driesbonte You need to be editing the **field** settings if it relates to an actual entry in the CMS. The _global_ settings, as you put it, are designed to be used with `craft.seo.custom()`.

If you head to `/admin/settings/fields` then find the field you're using for the entry (the `type` will be `SEO`) and click to edit it. In there, if you scroll down you'll see a **Page Meta** section where you can customise the data you're see in the sections it's attached to.
