### ISSUE TITLE
seo 3.7.0 migration error

### ISSUE THREAD

**Issue by SHoogland** [ethercreative/seo#350]
### Description
The latest updated gives an error when applying the migration

*** applying m201207_124200_add_product_types_to_sitemap
Exception: yii\db\mysql\QueryBuilder::dropCheck is not supported by MySQL. (/app/vendor/yiisoft/yii2/db/mysql/QueryBuilder.php:168)

### Steps to reproduce

1. with mariadb on docker or 10.2.37-MariaDB-log-cll-lve - MariaDB Server 
2. try to run the migration

### Additional info

- Craft version: 3.6.12
- SEO version: 3.7.0
- PHP version: 7.4
- Database driver & version: MySQL 5.5.5
- Other Plugins: not relevant

**Comment by jordanmoore** [comment]
Was literally about to open the same ticket. +1

**Comment by alexjcollins** [comment]
Thanks for flagging. We're taking a look

**Comment by unlockersnl** [comment]
Same here!
