### ISSUE TITLE
Duplicate Page never updates title in SEO Hook (FB & Twitter Meta info)

### ISSUE THREAD

**Issue by gbaumbach** [ethercreative/seo#352]
### Description
When you duplicate a page, the duplicate page inherits the original title and doesn't seem to update when you change the title or edit the SEO settings. I use the default {% hook 'seo' %} in my template.

### Steps to reproduce

1. Duplicate a page
2. Edit that page title and check the meta settings for FB title and Twitter
3. You can see the issue on this page's source code where I duplicated a previous page. The <title> updates, but not the FB/Twitter Meta.
https://www.awarerecoverycare.com/addiction-epidemic/first-responders

### Additional info

- Craft version:  3.6.13
- SEO version: Latest

**Comment by gbaumbach** [comment]
<img width="869" alt="Screen Shot 2021-05-05 at 2 12 37 PM" src="https://user-images.githubusercontent.com/3330559/117189324-1304e480-adac-11eb-8947-d62ea7c4d871.png">

You can see in the database table it still has the old title. Not sure how to update this besides updating the database itself.

**Comment by alexjcollins** [comment]
@gbaumbach What is the field showing on your entry, out of interest?

**Comment by gbaumbach** [comment]
First Responders as pictured here:
<img width="1472" alt="Screen Shot 2021-05-05 at 2 33 06 PM" src="https://user-images.githubusercontent.com/3330559/117191709-e1414d00-adae-11eb-9299-9e1f8b3029de.png">

**Comment by alexjcollins** [comment]
@gbaumbach Social meta isn't tokenised the same way as the primary meta values, so you'll need to tweak those manually. I notice the `Social` tab is missing from your screenshot, so you'll want to go to that field's settings and disable the hiding, so you can adjust those values.

![Screenshot 2021-05-06 at 05 52 24](https://user-images.githubusercontent.com/12031196/117243587-7126db80-ae2f-11eb-8ca1-036487d02fab.jpg)

**Comment by gbaumbach** [comment]
Gotcha, that did the trick. Thank you!

**Comment by alexjcollins** [comment]
Cool – glad i could help!
