### ISSUE TITLE
Error while updating to version 3.7.2 

### ISSUE THREAD

**Issue by karan-saluja** [ethercreative/seo#358]
### Description

Error while updating from 3.7.1 to 3.7.2.. 
I think there is a little problem with line number 110 of file "src/models/data/SocialData.php" which was changed in version 3.7.2.. 

### Steps to reproduce

1. Update SEO and go to a page that had SEO's "social image" uploaded 
2. Please see screenshot

### Additional info
![seo 3 7 2 error](https://user-images.githubusercontent.com/28668444/120213534-f1830580-c250-11eb-9319-5ee0dedbcf59.png)

- Craft version:3.6.15
- SEO version:3.7.2
- PHP version:7.2.24
- Database driver & version: MySQL 5.7.32 through PHP extension MySQLi
- Other Plugins:redactor, imager,craft3-calendar,contact-form,craft-campaign

**Comment by sunscreem** [comment]
Just to confirm, I've rolled back to version 3.7.1 and this has sorted it for me.

Same specs for my setup as Karan with the exception that I'm on PHP7.4

**Comment by rinusvandam** [comment]
I'm having the exact same error on version 3.7.3 with a site. 

- PHP version: 7.4.20
- OS version: Linux 4.9.0-15-amd64
- Database driver & version: MySQL 5.5.5
- Craft edition & version: Craft Pro 3.6.16

**Comment by cole007** [comment]
Likewise - looks like the stored image data is saved as a multidimensional array rather than an array of image objects to the is_array is always getting triggered but the stored data is not in the correct format.

Perhaps needs an array_key_exists check or similar in the logic for `/ether/seo/src/models/data/SocialData.php`

**Comment by karan-saluja** [comment]
Thanks Tam

**Comment by karan-saluja** [comment]
@Tam The images that were uploaded in the social tab are still not visible in the admin panel after the update
