### ISSUE TITLE
How do you set SEO field data programatically (PHP)

### ISSUE THREAD

**Issue by jakepm** [ethercreative/seo#368]
### Description

We are switching from a site that uses custom fields on entries to set SEO data.

The legacy fields are still in place, along with the new SEO field, for all relevant channels.

To copy over the existing SEO field values, we are planning to write a script that sets the SEO plugin field values for each entry by just reading from the legacy fields. Then we can delete those fields and update the template layouts to use the SEO hook.

My question is, what format should the data be in when setting a value for the SEO plugin field? I assume an array but am not sure what key values and structure to use.

PS. We only have the meta title and description in the legacy fields.

### Additional info

- Craft version: 3.7
- SEO version: 
- PHP version: 7.4
- Database driver & version:
- Other Plugins:

**Comment by alexjcollins** [comment]
@jakepm Is using Feedme not a possibility?

**Comment by jakepm** [comment]
Hadn't thought of building a data set that I can just import to update the SEO fields on all entries. I think this will do the job, so thanks for the suggestion @alexjcollins  :)

**Comment by alexjcollins** [comment]
@jakepm glad I could help 😊

**Comment by jakepm** [comment]
@alexjcollins unfortunately this does not solve our problem, as the SEO field shown in the FeedMe config does not provide any options for setting values per 'sub field'. Instead it provides just one input field, so we are back to not knowing what format the SEO plugin field data should be in.

**Comment by jakepm** [comment]
Managed to get this done by looking at https://github.com/ethercreative/seo/issues/306

Here's the code for anybody that finds this later, as the solution is not documented anywhere.

```
$json = [];
$articles = Entry::find()->section('articles')->all();

foreach ($articles as $a) {
	$json[] = [
		'slug' => $a->slug,
		'seo' => json_encode([
			'titleRaw' => [ "1" => $a->metaTitle ],
			'descriptionRaw' => $a->metaDescription,
		]),
	];
}

echo json_encode($json);
```

Once you have the data in this format, you can simply import via Feed Me. 
See the other issue for guidance on other fields like keywords.

**Comment by alexjcollins** [comment]
Thanks for posting this @jakepm

**Comment by jakepm** [comment]
@alexjcollins we actually missed a bug with this.

The social media titles for every post we updated via FeedMe (as shown above), seem to have been saved as an error output rather than copying the 'titleRaw' value. 

The social titles (Facebook, Twitter) for every post are: 

"ERROR: Trying to get property 'site' of non-object"

Any ideas about what went wrong here? 
Do we need to explicitly set the social titles in the JSON string for the FeedMe import?
