### ISSUE TITLE
Keyword tag bug in Safari 15 on Mac OS X

### ISSUE THREAD

**Issue by pixeldeluxe** [ethercreative/seo#378]
### Description
When try to add keyword tags in Safari 15 on Mac OS X, page will crash and directly redirect to entry overview view.

### Steps to reproduce
1. I open a sertain entry in Safari 15 on Mac OS X and go to the SEO tab.
2. There I try to add a keyword tag.
3. When I press enter the page will automatically redirect to the overview page.

### Additional info
PHP version: 8.0.11
OS version: Linux 3.10.0-1160.11.1.el7.x86_64
Database driver & version: MySQL 5.5.5
Image driver & version: Imagick 3.5.1 (ImageMagick 6.9.10-68)
Craft edition & version: Craft Pro 3.7.13
Yii version: 2.0.43
Twig version: v2.14.7
Guzzle version: 7.3.0
Invoegtoepassingen
CKEditor: 1.1.2
Contact Form: 2.2.7
CP Field Inspect: 1.2.5
Craft Commerce: 3.4.3
Expanded Singles: 1.1.4
Field Manager: 2.2.4
Mollie for Craft Commerce: 3.0.0
oEmbed: 1.3.12
Position Fieldtype: 1.0.17
reCAPTCHA: 1.5.2
Redactor: 2.8.8
SEO: 3.7.4
Site Utils: 1.2.20
Super Table: 2.6.8
Typed link field: 1.0.25
Wordsmith: 3.3.0.1

**Comment by alexjcollins** [comment]
@pixeldeluxe Following some testings I have observed the same problem on Craft 3.7.13. 
Luckily, updating to the latest version (at the time of testing 3.7.18) fixes the issue.
