### ISSUE TITLE
CSRF Javascript issue

### ISSUE THREAD

**Issue by caleuanhopkins** [ethercreative/seo#38]
SEO: v1.4.2
Craft: v2.6.2983

Javascript error. Happens as soon as I log in and head into the SEO menu panel from the left hand menu.

![screen shot 2017-06-21 at 10 51 01](https://user-images.githubusercontent.com/1164525/27378443-cbabff34-566f-11e7-96be-42d0d7e2959f.png)
![screen shot 2017-06-21 at 10 51 08](https://user-images.githubusercontent.com/1164525/27378444-cbb92c86-566f-11e7-97bb-cb911646932f.png)

**Comment by caleuanhopkins** [comment]
`controller/SeoController.php` line 65 needs to change to 
`craft()->templates->includeJs("new SeoSettings('{$namespace}', 'sitemap', [Craft.csrfTokenName, Craft.csrfTokenValue]);");`

If I get time this evening, I'll submit a PR with this change. This bug does stop users adding in custom urls into the sitemap.

**Comment by caleuanhopkins** [comment]
PR #39 submitted

**Comment by Tam** [comment]
Thanks, released a patch!

**Comment by caleuanhopkins** [comment]
@Tam sorry mate, I've done a new PR as the fix above fixed the error for the others pages, but missed the sitemap page. Didn't release two methods in that file were missing the CSRF tokens.

**Comment by Tam** [comment]
@caleuanhopkins On the bright side, we're now starting to match Crafts update frequency 🤣
Thanks, I've pushed another release.
