### ISSUE TITLE
Redirect to external link not working

### ISSUE THREAD

**Issue by mateostabio** [ethercreative/seo#381]
I am trying to add redirects to another subdomain name as the website is moving place.
I will be leaving the current site where it is, and building a new one. Setting up redirects here pointed to another subdomain.

### Steps to reproduce

1. I am trying to redirect each page: blog/success-stories/community-experience-revenue
2. Pointing them to their new location: https://www.newdomain.com/blog/community-experience-revenue
3. I don't know if it's not working because I'm not doing something right.
4. Good to mention that this is a multi-site with 2 languages. I did try different options, selecting ALL SITES, ENGLISH and FRENCH. None of which have worked.

### Additional info

- Craft version: Craft CMS 3.5.7
- SEO version:  SEO 3.6.6
- PHP version:	 7.4.25
- Database driver & version: MySQL 8.0.23

**Comment by alexjcollins** [comment]
If the current URL doesn't 404, then the SEO redirects won't be engaged. We only check the redirect table if Craft returns a 404, reducing the request overhead.

**Comment by mateostabio** [comment]
Thank you for that! Disabling the entries worked!

**Comment by alexjcollins** [comment]
Great! Glad that sorted it for you 😊
