### ISSUE TITLE
Main page not displaying in Craft 3.7.25

### ISSUE THREAD

**Issue by nathanaeljames** [ethercreative/seo#382]
### Description

Any reason this does not seem to be displaying the main page when freshly installed on Craft 3.7.25? Is anybody else having this issue or am I overlooking something? 

<img width="783" alt="Screen Shot 2021-12-07 at 9 19 51 PM" src="https://user-images.githubusercontent.com/56363552/145139039-7ec801bc-e388-45a3-a5f5-a7272fdcb234.png">

### Steps to reproduce

1. Install Plugin
2. Go to dashboard

### Additional info

- Craft version: Craft Pro 3.7.25
- SEO version: 3.7.4
- PHP version: 7.4.3
- Database driver & version: MySQL 8.0.27
- Other Plugins:
Contact Form         2.2.7
Google Tags	        1.3.0
Redactor.                2.8.8
SEO.                         3.7.4
Super Table	        2.7.0
Template Guard	1.0.0

**Comment by alexjcollins** [comment]
Hey @nathanaeljames I just set SEO up on a fresh install and the dashboard shows ok. 

Is the screenshot you've attached what you expect to see?
And if so, what do you actually see when you go to the SEO navigation item?

My only suggestion at this stage would be try uninstalling and reinstalling?

**Comment by nathanaeljames** [comment]
Greetings @alexjcollins , clicking 'SEO' also takes me to the dashboard, but the above is not what I expect to see. I cannot find anywhere within the app the screen which allows me to see the Optimisation and previews of the pages. Where can I see that?

**Comment by alexjcollins** [comment]
Ah, I see what you mean, now.

So that stuff is only available on the custom field. So, you'll want to create a new field and set the type to `SEO`. Then add that field to a section. When you create an entry in that section, you'll see the SEO field along with all the page analysis and optimisation fields/features.

**Comment by nathanaeljames** [comment]
@alexjcollins ah, my bad. Thank you!
