### ISSUE TITLE
 Meta title always contains site name

### ISSUE THREAD

**Issue by therealpecus** [ethercreative/seo#387]
### Description

This has the same symptoms as #376 but the cause might be different. I am using the plugin per instructions, but it seems that once entries have been updated with the seo field, a change in the title token configuration is not propagated.
The field is mapped to "update for every site". 

I understand that this might be by design, since a change to a token might overwrite any personalization the user has made, but this effectively aborts the title field management and is not documented.

### Steps to reproduce

1. Install plugin
2. Create seo field
3. Add seo field to site sections
4. Update template
5. Display a page, note the title (it includes the site name)
5. Change the `{{ sitename }}` token to anything else (say, `| BLM`). You can also remove it and add a new token. Save changes
6. Display a page, note the title (it includes the site name, while instead it should show `BLM`)

### Additional info

- Craft version: CMS 3.5.19.1
- SEO version: 3.7.4
- PHP version: 7.4.24
- Database driver & version: MySQL 5.7.35
- Other Plugins: 
Contact Form 2.2.7
Contact Form Honeypot 1.0.2
Field Manager 2.2.4
Redactor 2.8.5
Redactor Custom Styles 3.0.4
Tags 1.0.9

**Comment by andreimoment** [comment]
In my case the meta title repeats the site name twice, regardless of the content of the title field. Also, the description field remains empty regardless of the content of the description field provided on the page.

**Comment by therealpecus** [comment]
+1 This is happening to me

Changing tokens or any part of the tile in the plugin config does not seem to resave entries updating the seo field.

**Comment by therealpecus** [comment]
I figured it out, but the documentation might benefit of an improvement.
Settings for the plugin do not propagate to SEO **fields** that have already been created. You have to edit the actual field.

**Comment by jon-collette** [comment]
> I figured it out, but the documentation might benefit of an improvement. Settings for the plugin do not propagate to SEO **fields** that have already been created. You have to edit the actual field.

I'm not entirely certain this is expected behavior as SEO > Settings > Page Meta (under `/admin/seo/settings` ) do not propagate to the entries. Instead, you update the Field > Page Meta values instead (under `/admin/settings/fields`).

I'm not certain why there are duplicate settings unless `SEO > Settings > Page Meta` is defining the default values to use as new field creation but generally it's confusing.
