### ISSUE TITLE
Redirect not working when an entry exists

### ISSUE THREAD

**Issue by kevinmu17** [ethercreative/seo#391]
### Description
I'm trying to add some redirects for a client but they do not work.

When doing something simple like 'test' > 'test2' it is working absolutely fine. But when trying to redirect an URI while an entry exists on that URI the redirect doesn't do a thing. Is this by design?

### Steps to reproduce
1. create a single entry like 'notworking'
2. Add SEO redirect '/notworking' to '/notworking2'

### Additional info
- Craft version: 3.7.34
- SEO version: 3.7.4
- PHP version: 8.0.13
- Database driver & version: MariaDB 10.3
- Other Plugins: N/A

**Comment by hadyfarhat97** [comment]
Same here.

When I enter a URI that's associated with an entry, the redirect doesn't work. However, when I enter a random URI that's no associated with an entry, the redirect works

**Comment by masiorama** [comment]
Same here. +1

**Comment by alexjcollins** [comment]
That is the intended behaviour - we only run a lookup in the redirects table when Craft returns a 404.
The idea behind this is to remove the need to query the redirects on every request.

It's possible to use `{% exit 404 %}` in templates to force a redirect. [Changlog](https://github.com/ethercreative/seo/blob/67ce1f13d5bf33e9bf7453b3fa2cbe5c8d79a6f4/CHANGELOG.md#361---2019-07-26).

**Comment by masiorama** [comment]
@alexjcollins I see, so in order to fix it  a solution could be this, on top of the template, right?

```
{% if (craft.app.request.getSegment(1) == 'oldurl')%}
    {% exit 404 %}
{% endif %}
```
Thanks

**Comment by alexjcollins** [comment]
Yeah, exactly 👍
