### ISSUE TITLE
[error] Class name must be a valid object or string

### ISSUE THREAD

**Issue by JordanMed** [ethercreative/seo#393]
### Description
I just started to receve this server error when opening an entry that has the seo plugin. 

2022-03-25 12:23:10 [-][1][2i99ol1tosuh670t953in8mlr1][error][Error] Error: Class name must be a valid object or a string in /var/www/vendor/ether/seo/src/controllers/SeoController.php:62
Stack trace:
#0 [internal function]: ether\seo\controllers\SeoController->actionRenderData()
#1 /var/www/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#2 /var/www/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#3 /var/www/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('render-data', Array)
#4 /var/www/vendor/craftcms/cms/src/web/Application.php(287): yii\base\Module->runAction('seo/seo/render-...', Array)
#5 /var/www/vendor/craftcms/cms/src/web/Application.php(596): craft\web\Application->runAction('seo/seo/render-...', Array)
#6 /var/www/vendor/craftcms/cms/src/web/Application.php(266): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#7 /var/www/vendor/yiisoft/yii2/base/Application.php(384): craft\web\Application->handleRequest(Object(craft\web\Request))
#8 /var/www/html/index.php(21): yii\base\Application->run()
#9 {main}
2022-03-25 12:23:09 [-][1][2i99ol1tosuh670t953in8mlr1][info][application] $_GET = [
    'p' => 'admin/defaultactions/seo/seo/render-data'
]

### Steps to reproduce

1. Open any page with the SEO plugin
2. Receive the error.

### Additional info

- Craft version: 3.7.27.1
- SEO version: 3.7.4
- PHP version: 7.4.21
- Database driver & version: MySQL 5.7.12
- Other Plugins:

**Comment by alexjcollins** [comment]
Did it coincide with any updates?
If you're getting the issue locally, it might be worth deleting your vendor folder and reinstalling?

**Comment by JordanMed** [comment]
This was an issue with my EC2 server
