### ISSUE TITLE
Does the sitemap updates automatically?

### ISSUE THREAD

**Issue by NicolasBarse** [ethercreative/seo#394]
### Description

Recently I noticed that some of my entries were not in the sitemap. I first thought it was a mistake and verified on the google search console but the urls were not crawled. I simply saved the sitemap and resubmitted it and everything seemed to work fine. Is it possible that the sitemap doesn't update automatically?

### Additional info

- Craft version: 3.6.11.1
- SEO version: 3.6.7
- PHP version: 7.3.27

**Comment by alexjcollins** [comment]
Hey @NicolasBarse! Yeah, the sitemap should be updating automatically when a new entry is added/removed.

It might be worth manaully checking the sitemap the next time you make a content change that would affect it, to make sure it's definitely being added in your case.

If it's not, feel free to reach back out. Thanks!
