### ISSUE TITLE
[FR] Sitemap.xml graphql endpoint

### ISSUE THREAD

**Issue by maximilian-schwarz** [ethercreative/seo#396]
### Description
I think it's very important to have the possibility get the sitemap via Graphql to generate a sitemap.xml for headless project wiht NuxtJS oder NextJS.

Maybe the response can look like this:

```
"sitemap": {
  "filename": "sitemap_pages.xml",
  "content": "<?xml version=\"1.0\" encoding=\"UTF-8\"?> <urlset xmlns=\"http://www.sitemaps.org/schemas/sitemap/0.9\"><url><loc>http://www.example.com/foo.html</loc><lastmod>2018-06-04</lastmod></url></urlset>"
}
```

**Comment by alexjcollins** [comment]
Hey @maximilian-schwarz - we're in the process of rewriting the plugin for Craft 4, so we'll absolutely consider this.

In the meantime, certainly with NextJS, you can use rewrites to map to the URL of your craft install.

Something like this:

```js
async rewrites() {
  return [
    {
      source: '/sitemap.xml',
      destination: `${process.env.ADMIN_URL}/sitemap.xml`,
    },
    {
      source: '/sitemap:path.xml',
      destination: `${process.env.ADMIN_URL}/sitemap:path.xml`,
    },
    {
      source: '/robots.txt',
      destination: `${process.env.ADMIN_URL}/robots.txt`,
    },
  ];
},
```

**Comment by maximilian-schwarz** [comment]
Thanks for the tip 👍🏻
