### ISSUE TITLE
Craft 4 Support

### ISSUE THREAD

**Issue by idawgik** [ethercreative/seo#398]
I know it's only been a couple days since Craft 4's release, but just wanted to check if there's an estimated timeframe on compatibility for it. This is a plugin we use on most of our client's websites, so we won't be able to do any updates until this is compatible. Just want to be able to set expectations for clients.

Thank you!

**Comment by niektenhoopen** [comment]
I created this pull request #397 just before v4 was launched. Still haven't received any feedback so if you (and others) could test my fork, that would be awesome.

**Comment by jesuismaxime** [comment]
@Tam 👆

**Comment by alexjcollins** [comment]
We'll check out the PR early next week, all. Enjoy the weekend.
