### ISSUE TITLE
Craft 4 - Key "heading" for array with keys "manageSitemap, manageRedirects" does not exist.

### ISSUE THREAD

**Issue by kevinmu17** [ethercreative/seo#399]
### Description
When going into a user settings or user group settings craft throws an error:
`Key "heading" for array with keys "manageSitemap, manageRedirects" does not exist.`

### Steps to reproduce
1. Instal plugin
2. Navigate to your admin account settings (top right)

### Additional info

- Craft version: 4.0.1
- SEO version: 4.0.0
- PHP version: 8.0.17
- Database driver & version: MariaDB 10.3
- Other Plugins: N/A

**Comment by niektenhoopen** [comment]
@kevinmu17 I've created a pull request for this issue. It's not merged yet but maybe you could verify if that solves your problem.

**Comment by jacobgraf** [comment]
I originally filed this here (https://github.com/craftcms/cms/issues/11236) but @niektenhoopen I pulled in the changes in your PR and it fixed the issue for me! Thanks! Hopefully Ether deploys a hotfix soon!

**Comment by remcoov** [comment]
Please fix this. I can't even create a new usergroup or get to my admin settings.

**Comment by kevinmu17** [comment]
Seems like it isn't synced on packagist yet, can you confirm @Tam ?

**Comment by dejury** [comment]
@kevinmu17 @Tam see issue #405. Please check this out for a moment, waiting for packagist to sync.
