### ISSUE TITLE
Social cards do not seem to propagate on social media?

### ISSUE THREAD

**Issue by Grant-Smith-74** [ethercreative/seo#403]
### Description

The social cards that can be created do not seem to propagate on social media? Meta tags appear correct…
And the cards are filled correctly. However, if I paste the url into LinkedIn, I get some old test data?

Screenshots are attached to the below discord thread.

https://discord.com/channels/456442477667418113/575387375610626063/974656335285207060

### Additional info

- Craft version: Craft Pro 3.7.38
- SEO version: 3.7.4
- PHP version: 8.0.18
- Database driver & version: MySQL 5.7.37
- Other Plugins:
Contact Form | 2.5.0
Contact Form Honeypot | 1.0.2
Fetch | 1.3.0
MobileDetect | 1.0.2
Navigation | 1.4.25
Redactor | 2.10.6
Sprig | 1.12.4

**Comment by alexjcollins** [comment]
Hey @GrantSmithDoddle 👋

If the page has been shared (or even loaded) previously to social with different content, it may be cached by the network.
To purge the cache you can use the tools from each of the networks:

LinkedIn: https://www.linkedin.com/post-inspector/
Twitter: https://cards-dev.twitter.com/validator
Facebook: https://developers.facebook.com/tools/debug/

I ran the URL in the LinkedIn Post Inspector, and it looks like it has picked up your new content.

![Screenshot 2022-05-17 at 1 02 56](https://user-images.githubusercontent.com/12031196/168806680-3285f48e-4fa2-4ce9-80d8-e5782e7c4d30.jpg)
