### ISSUE TITLE
Sitemap Sections Issue

### ISSUE THREAD

**Issue by zadro** [ethercreative/seo#409]
### Description

Sitemap.xml is working as expected. However, any of the sitemap section files, ie. "sitemap_sections_1_0.xml" is throwing an error:

Calling unknown method: craft\models\FieldLayout::getFields()

in /home/user/craft/vendor/ether/seo/src/services/SitemapService.php at line 316 – [yii\base\Component::__call](http://www.yiiframework.com/doc-2.0/yii-base-component.html#__call()-detail)()

```
        {
            $fieldLayout =
                $variables['section'] === 'categories' || $variables['section'] === 'productTypes'
                    ? $first->fieldLayout
                    : $first->type->fieldLayout;
 
            foreach ($fieldLayout->getFields() as $field)
                if (get_class($field) === SeoField::class)
                    $seoFieldHandle = $field->handle;
        }
 
        foreach ($elements->all() as $item)
        {
```

### Steps to reproduce

1. Enabled "dev" mode 
2. Navigated to any sitemap section file

### Additional info

- Craft version: 4.0.3
- SEO version: 4.0.0
- PHP version: 8.1.6
- Database driver & version: MariaDB 10.5.16-MariaDB-1:10.5.16
- Other Plugins: Redactor 3.0.0

**Comment by zadro** [comment]
Per this update: https://github.com/nystudio107/craft-seomatic/releases/tag/4.0.0-beta.6

It looks like the fix is to change `getFields()` to `getCustomFields()`

Please merge and update.

**Comment by moondawg69** [comment]
@zadro I too can confirm the above issue, be nice if it could become a quick fix :)

**Comment by niektenhoopen** [comment]
@zadro I have implemented your suggestion and it seems to work. I have created PR #410 for it

**Comment by AnthonyLaSala** [comment]
This also fixed my unrelated `Calling unknown method: craft\models\FieldLayout::getFields()` issue. Just commenting this so it is more searchable for people. This fix was not easy to find
