### ISSUE TITLE
Focus Keywords in single entry is not available

### ISSUE THREAD

**Issue by interactivespace** [ethercreative/seo#417]
### Description
When I add the seo field to a single entry, I can't use the focus keywords feature. Am I missing an important configuration stepp?

Error: Focus Keywords, This feature is not available.

If the feature is not usable, how could I remove it completly?

### Additional info

- Craft version: Craft Solo 4.0.5.2
- SEO version: 4.0.3
- PHP version: 8.1.7
- Database driver & version: MySQL 10.3.35
- Other Plugins: Blitz Cache, ImageOptimize, Contact Form, Honeypot

**Comment by charliestrafe** [comment]
I am also experiencing this issue. Is there any update on this, did you find a fix @interactivespace ?
![Screenshot 2022-07-13 at 09 18 30](https://user-images.githubusercontent.com/47243887/178685819-7335ae37-3b1b-4b4b-be4a-98df170347cd.png)

**Comment by interactivespace** [comment]
I didn't had much time left for this project. There where some more issues and i couldn't find time to dig deeper. So I changed to the paid SeoMatic plugin. The focus keywords are nice to have and the SeoMatic plugin doesn't provide this feature. But I think most clients who  really needs good SEO texts let them create from agencies and this agencies use their own tools.

I actually choose this plugin first because of the focus keyword feature. Many clients have some experience with WordPress and the Yoast plugin and they are not happy, when a cms doesn't include a feature like that.

**Comment by alexjcollins** [comment]
Sorry, I missed this one!

If you're using Craft in [`headlessMode`](https://craftcms.com/docs/3.x/config/config-settings.html#headlessmode), we disable the feature.
It would probably make more sense to remove that section rather than disable it, though.

**Comment by charliestrafe** [comment]
Thanks for the feedback. @alexjcollins my website isn't using headlessMode, and I've tried switching my environments to dev, staging and production and it doesn't work in any of them.

**Comment by alexjcollins** [comment]
@charliestrafe Do you have Live Preview enabled (have preview targets set up) on the sections you're using the field on?
The feature analyses the contents of the live preview, so that needs to be running, too.

**Comment by masiorama** [comment]
In my case, the function is working on my single pages, but it does not work on commerce product pages.

**Comment by alexjcollins** [comment]
@masiorama Is live preview set up and working on your product pages?

**Comment by masiorama** [comment]
Live preview does work for product pages. The only part not working is your plugin's Focus Keyword section.

**Comment by alexjcollins** [comment]
What error are you getting?

**Comment by masiorama** [comment]
The very same screen @charliestrafe posted, with message "the feature is not available".
No error in chrome console.

**Comment by alexjcollins** [comment]
After investigation, it looks like focus keywords are now broken on products.

Given this issue relates to single-type sections, I'm going to close this and open a separate issue for products.
