### ISSUE TITLE
Site name is not updating 

### ISSUE THREAD

**Issue by wallythewebdev** [ethercreative/seo#421]
### Description

Site name is not updating - it is showing the previous URL from my nitro site: 

`<meta property="og:title" content="home - http://test.nitro">`

<img width="869" alt="image" src="https://user-images.githubusercontent.com/28821463/179461391-fb037b5a-efd6-4de2-a4db-7523509fd569.png">

How do I go about updating this field or clearing any cache left over from my local build? 

Any help would be greatly appreciated as I've bee going around in circles for a while now. 
Thanks - W

### Additional info

- Craft version: Craft Solo 4.1.4.1
- SEO version: v4.0.3
- PHP version: 8.1.8
- Database driver & version: MySQL 10.3.35
- Other Plugins:

**Comment by wallythewebdev** [comment]
Answer: 

Because the site name had been set at the page level (by the global rule) - the page level overwrites the global default. Deleting the SEO tags at the page level (i.e. in the home page - SEO field) allowed for the values to reset.

**Comment by alexjcollins** [comment]
Thanks for following up here @wallythewebdev and glad you got it sorted 💪
