### ISSUE TITLE
Keywords are not rendered in template

### ISSUE THREAD

**Issue by Kota-M** [ethercreative/seo#446]
### Description
I would like to insert keywords which are set in Craft back-end, with the plugin. However, keywords are not rendered in the template. How can I render them?

I already tried it, but "Array to string conversion" error occurs.
`<meta name="keywords" content="{{ seo.keywords|join(', ') }}" />`

### Additional info
- Craft version: 3.7.57
- SEO version: 3.7.4

**Comment by Kota-M** [comment]
I found it by myself. My additional code for meta.twig is;

```
{% set keywords_string = "" %}
{% set is_first_keyword = true %}
{% for item in seo.keywords %}
	{% if is_first_keyword %}
		{% set keywords_string = item.keyword %}
		{% set is_first_keyword = false %}
	{% else %}
		{% set keywords_string = keywords_string ~ ", " ~ item.keyword %}
	{% endif %}
{% endfor %}
{% if keywords_string|length > 0 %}
	<meta name="keywords" content="{{ keywords_string }}" />
{% endif %}
```

**Comment by alexjcollins** [comment]
@Kota-M Thank you for following up with your solution. I'm going to close this issue, but if you have any other questions or issues, do let us know.
