### ISSUE TITLE
URL for alternate locale is invalid

### ISSUE THREAD

**Issue by ClemensSchneider** [ethercreative/seo#45]
When looking at the URLs for alternate locales in a multi-locale site we observed incorrect (non-existing) URLs being generated.

Example:

```
  <url>
    <loc>http://localhost:9000/0002_0015_heardis-website/de/work/deutsche-bundesbank/ein-lernort-zum-thema-geld</loc>
    <lastmod>2017-09-25</lastmod>
    <changefreq>weekly</changefreq>
    <priority>0.9</priority>
    <xhtml:link rel="alternate" hreflang="en" href="http://localhost:9000/0002_0015_heardis-website/en/work/deutsche-bundesbank/ein-lernort-zum-thema-geld"/>
  </url>
```

The correct URL for the english version of the page is `http://localhost:9000/0002_0015_heardis-website/en/work/deutsche-bundesbank/a-learning-experience-on-money` instead.

Take a look at the pull-request I'm going to push. It correctly works for `entries` and `categories` but I'm unsure in the context of craft-commerce.

**Comment by Tam** [comment]
Merged in latest release!
