### ISSUE TITLE
Plugin store displays message: This plugin is no longer maintained.

### ISSUE THREAD

**Issue by ludo-evo** [ethercreative/seo#450]
### Description

The page for this plugin on the Craft CMS plugin store displays the following message: This plugin is no longer maintained.
Yet a new version was released recently.
Should we worry?

### Steps to reproduce

1. Go to the Craft CMS plugin store
2. Search for the SEO plugin
3. Stare at the message

### Additional info

- Craft version: 4.4.7
- SEO version: 4.1.0
- PHP version: 8.0.3
- Database driver & version: MySQL 5.7.32
- Other Plugins: 

Feed Me | 5.1.1.1
Redactor | 3.0.4
Sprig | 2.5.1
Vite | 4.0.5

![image](https://user-images.githubusercontent.com/120502382/231811451-3db03c1f-b8b0-4708-9a20-6ee553d2b320.png)

**Comment by alexjcollins** [comment]
Labelling it was something Pixel & Tonic did whilst we planned the future of the plugin. If we decided to contiunue managing it, we would remove the label after the first update that resolves some of the key issues.

We plan to continue to support it for the foreseeable future.
