### ISSUE TITLE
Spacing bug between page title and site name

### ISSUE THREAD

**Issue by pascalminator** [ethercreative/seo#452]
### Description
There is an annoying spacing bug between page title and site title, that appeared with the latest update of this plugin. It caused this problem on all the websites I updated so far. For example, before the update it was 'Page title - Site name' and now it is 'Page title- Site name'.

The spacing is properly defined (it is by default anyway) in the settings:
![image](https://user-images.githubusercontent.com/13754636/234890549-53ab1116-3923-4293-9d17-8b7255a410b8.png)

But ignored in the entries:
![image](https://user-images.githubusercontent.com/13754636/234891394-f32a1b46-0f96-40bd-91b7-91e54cd3e51a.png)

### Steps to reproduce

1. Update the SEO plugin to latest version
2. Visit an entry with the SEO field used to set the page title and save
3. Open the saved page in front-end and look at the title with the newly missing spacing (Page title- Site title)

### Additional info

- Craft version: 4.4.8
- SEO version: 4.1.1
- PHP version: 8.2

**Comment by pascalminator** [comment]
So after investigation, this problem is caused by a Craft CMS update rather than an update from the SEO plugin. I updated Craft on a different site, without updating the SEO plugin, and the problem still occure. 

Basically, the space after the page title is ignored / removed: 

![image](https://github.com/ethercreative/seo/assets/13754636/88dbafb3-bf19-4cd3-9539-842e68a4c716)

This is happening on absolutely all my websites using this SEO plugin, after the Craft update of 3 weeks ago.

**Comment by alexjcollins** [comment]
Thanks for the additional info; we'll take a look.

**Comment by pascalminator** [comment]
This issue is now also affecting the SEO plugin on Craft 3. I have a few websites on Craft 3 that were recently updated and are now getting this exact same problem: the space after the page title is ignored / removed. 

![image](https://github.com/ethercreative/seo/assets/13754636/4003467b-987f-4f93-b519-672e3af0a80c)

The website in this screenshot was developed back in 2021 and never had this issue before. 

Weirdly enough, it looks like it only affects the <title> and not the Twitter and Facebook titles:

![image](https://github.com/ethercreative/seo/assets/13754636/59a76085-2266-42ce-9360-651e1f1bdc26)
