### ISSUE TITLE
Default page description in settings & entries are different

### ISSUE THREAD

**Issue by ejaedesign** [ethercreative/seo#455]
### Description
The default page description in Settings is different than what's showing up as "default" in the page description per entry. I also can't find where the text is coming from. 

### Steps to reproduce

1. Go to Settings and check page description
2. Go to an entry and check page description

Where is the place I can edit the default page description and if it's in the Settings, why is it different than what's showing in each entry's description field?

When I edit the "default" description in the entry, the new description does show up with the {{ seo.description }} tag. 

Thanks in advance!

**Comment by alexjcollins** [comment]
Hi @ejaedesign 
Just so I'm clear, have you added an SEO field to the entries you're referencing? As you can also set defaults in the field when you create that.
Thanks

**Comment by ejaedesign** [comment]
Hi Alex,
Yes, the seoField is available in every section. Do I go into the field settings to change the default description?
Thanks for the quick response!

**Comment by ejaedesign** [comment]
Nope, I answered my own question here. I found it in the field settings indeed!

Also, is there a way to output the Focus Keywords that are entered in each entry?

**Comment by alexjcollins** [comment]
Yeah, if you're using the field on an entry, you will want to edit the defaults there (field settings).

The global defaults are more for use in templates that aren't represented in a Craft section, such as a static template that doesn't need full CMS integration.

Hope that helps!

**Comment by ejaedesign** [comment]
Got it.

Now, is there a way to output the focus keywords? {{ seo.keywords }} or similar?

**Comment by alexjcollins** [comment]
Sure, although [we don't include them in our meta template](https://github.com/ethercreative/seo/blob/v4/src/templates/_seo/meta.twig), because they're not used by Google for ranking.

This snippet should work:

```
{% for k in entry.seo.keywords %}
    {{ k.keyword }}
{% endfor %}
```

**Comment by ejaedesign** [comment]
Great. Thanks so much, Alex!
