### ISSUE TITLE
502 error caused when saving entry with validation errors whilst using the plugin

### ISSUE THREAD

**Issue by andrewhawkes** [ethercreative/seo#478]
### Description

It seems the SEO plugin is causing a 502 error when you try to save an entry with a field validation issue.
For example, a required field does not have a value or a text field is over the max character length.

This originates from an issue on Craft CMS https://github.com/craftcms/cms/issues/14867. See [i-just](https://github.com/i-just)'s comments for further details.

### Steps to reproduce

1. Add SEO field to an entry type
2. Try save the entry with a validation issue
3. 502 error is thrown

### Additional info

- Craft version: 5.0.5
- SEO version: v5.0.0-rc1
- PHP version: 8.2.15

**Comment by Tam** [comment]
Fixed in v5.0.0-rc2
