### ISSUE TITLE
[FR] Auto-expand SEO score detail

### ISSUE THREAD

**Issue by hisnameisjimmy** [ethercreative/seo#51]
As a user, I want to see the details of my score without having to click, so that I have a more immediate understanding of my score.

Unless this is saving a significant amount of resources to hide this by default, I'm not sure it makes sense to hide this information behind a click. 

![5_apps_that_make_you_a_smarter_sales_rep_-_badger_website](https://user-images.githubusercontent.com/740373/34214942-2a276cc4-e5a4-11e7-8bb9-e8ec18081102.png)

**Comment by Tam** [comment]
Updated in latest release!
