### ISSUE TITLE
[FR] Locale support when generating sitemap

### ISSUE THREAD

**Issue by traffic-nz** [ethercreative/seo#52]
The sitemap feature is great, but it would be even better if the sitemaps automatically didn't include pages that are turned off, especially pages that are turned off for certain locales. Or, allow the user the option to not include pages that are currently turned off when generating the sitemap. Google Search Console is lit up right now with loads of 404s for pages that are in the sitemap but only turned on for one locale and not the others. Thank you!!!!

**Comment by Tam** [comment]
Fixed in latest release!
