### ISSUE TITLE
Internal Server Error when accessing the Sitemap page after upgrading

### ISSUE THREAD

**Issue by fdelaneau** [ethercreative/seo#63]
I have the following error message after upgrading the plugin and trying to access the Sitemap page

```
Internal Server Error
Craft\Seo_SitemapRecord and its behaviors do not have a method or closure named "enabled".
```

PS. I’ve updated Craft before upgrading the plugin.

**Comment by Tam** [comment]
What version of Craft & the plugin are you using?

**Comment by fdelaneau** [comment]
Hi,

I since solved the problem by uninstalling, then reinstalling the plugin.

I am using the latest Craft 2 release and downloaded the Craft 2 version of your plugin on GitHub after being noticed by craft that there was an update available.

Regards,
Fabrice Delaneau
