### ISSUE TITLE
[BUG] Optimisation Checklist - doesn't count the right amount of words

### ISSUE THREAD

**Issue by chemelb** [ethercreative/seo#65]
When counting the words the amount of total of words is incorrect [BUG]

**Comment by Tam** [comment]
What version of the plugin are you using?

**Comment by matevisky** [comment]
I have the same issue. 3.1.0. We have 400+ words and counting only 100
![seo_error](https://user-images.githubusercontent.com/264663/37187009-2e566236-23ad-11e8-96fe-a74e1d7db96f.png)
Do we have to use special tag or something to make it count?

![seo2](https://user-images.githubusercontent.com/264663/37187371-e69fc4b2-23ae-11e8-80d2-16853ed4613c.png)
Thank you
