### ISSUE TITLE
Recent Craft update has broke styling

### ISSUE THREAD

**Issue by JMKelley** [ethercreative/seo#67]
Just updated to the latest Craft 2.x and the styling of elements has completely removed (also some JS)

**Comment by Tam** [comment]
I can't replicate this, could you send me a screenshot?

**Comment by JMKelley** [comment]
Please see below:

![image](https://user-images.githubusercontent.com/2053555/36900768-8d12e1be-1e1c-11e8-89a5-c22fc62d98cf.png)

![image](https://user-images.githubusercontent.com/2053555/36900775-977d89a6-1e1c-11e8-958d-4f86cf46572e.png)

No errors via Console. I am using Cloudflare to minify the CSS/JS. Would that have anything to do with it?

**Comment by Tam** [comment]
I'm not sure what `SocialPoster.css` is, it's not one of SEO's CSS files. Some of the styling is working correctly (i.e. the tabs, they're custom) so it's possible that Cloudflare is corrupting the files, but it could also be that the files were not deployed to your server correctly.

I'd suggest re-uploading/deploying the plugin files again, and disabling Cloudflare to see if that helps.

**Comment by JMKelley** [comment]
I'll try re-uploading as well as stop Cloudflare minifying that file.

Are you on the Craft Slack Channel for further debug?

**Comment by Tam** [comment]
I'm around, but might be slow to respond!

**Comment by Tam** [comment]
@JMKelley Is this still an issue?

**Comment by JMKelley** [comment]
@Tam It was CloudFlare breaking the styling. Hard refresh fixes it.
