### ISSUE TITLE
Social image URL is incorrect

### ISSUE THREAD

**Issue by jeremyfuksa** [ethercreative/seo#69]
### Description
Social images have `siteUrl` displayed twice in the URL, thus making them broken.

e.g. "http://jeremyfuksa.com/jeremyfuksa.com/images/_1200x600_crop_center-center_none/GTY_kotter_watn_cast_3_dr_110307_3x2_1600.jpg"

^ Should only have one jeremyfuksa.com in the URL.

### Steps to reproduce

1. Add an image to an entry via the Social tab
2. View source

### Additional info

- Craft version: Craft Personal 3.0.0-RC13
- SEO version: 3.1.0
- PHP version: 7.0.27
- Database driver & version: MySQL 5.7.20
- Other Plugins: Parsedown, Minify, Typogrify

**Comment by Tam** [comment]
Is your site URL set to `jeremyfuksa.com`, not `http://jeremyfuksa.com`?

**Comment by jeremyfuksa** [comment]
I found the problem. It was in the way I set up my Assets folder. Craft's instructions are incorrect:

> The base URL to the assets in this volume. An absolute URL (“http://example.com/path/to/folder”) or protocol-relative URL (“//example.com/path/to/folder”) is recommended. It can begin with an alias, such as @web.

I had put `//jeremyfuksa.com/images/` as the path, and that was what was what was doing it. Changing that to `/images/` fixed it.
