### ISSUE TITLE
Redirects using query string no longer work

### ISSUE THREAD

**Issue by FreekVR** [ethercreative/seo#70]
### Description
Our client site migrated to craft from an old CMS using URL's like /page.php?id=12 to access content. We want to add redirects from these pages to a craft URL, but the recent changes in #47 are stripping all the parameters from the matched path.

I think perhaps there should be a global option whether to ignore query strings when matching URLs? As it seems to differ per site what the desired behaviour is.

### Steps to reproduce

1. Create a redirect from /page\.php\?id=12 to /some-url
2. Navigatie to /page.php?id=12
3. Get a 404

**Comment by Tam** [comment]
Fixed!
