### ISSUE TITLE
Don't use 'seo' as variable name in the default meta template.

### ISSUE THREAD

**Issue by dowadidi** [ethercreative/seo#71]
Not really a bug.

I have a global group named seo. That conflicted with https://github.com/ethercreative/seo/blob/v3/src/templates/_seo/meta.twig.

You could also mention it in the documentation not to use 'seo' as a global set name. But I think it is more user friendly to prevent it all together by using a very random variable name.

**Comment by Tam** [comment]
Giving the SEO variable a very random name would be less user friendly, especially for those of us using `craft.seo.custom`. If it's an issue for you, you can easily replace the meta template with your own (see the plugin settings page).

**Comment by dowadidi** [comment]
That's how I solved it. And if anyone else would have the same issue, the might stumble upon this solved issue.

Thank you for the plugin by the way!
