### ISSUE TITLE
Issues with category templates

### ISSUE THREAD

**Issue by kristoffer1lundberg** [ethercreative/seo#77]
### Description

Seems to give 'internal server error occurred' when trying to access a category element via twig template, but only when devMode is disabled.

### Additional info

- Craft version: Craft Pro 3.0.0-RC15
- SEO version: 3.2.2
- PHP version: 7.1.14
- Database driver & version: MySQL 5.5.5

**Comment by Tam** [comment]
Could you send me any log data you have from that error?

**Comment by Tam** [comment]
@kristoffer1lundberg Is this still an issue?

**Comment by kristoffer1lundberg** [comment]
@Tam Oh, sorry, I forgot to reply to this... No, this seems to be working now!
