### ISSUE TITLE
Force Default Title Suffix

### ISSUE THREAD

**Issue by rinusvandam** [ethercreative/seo#78]
I'm using SEO on a new Craft site.
My client added +100 entries of different content types.

Our title structure was: Title - Foo
Now we want to change the title suffix for all entries to: Title - The New Foo

Is there any way to force a new suffix to all entries?

- Craft version: 3.0.0-RC16.1
- SEO version: 3.2.2
- PHP version: 7.2.1

**Comment by Tam** [comment]
We don't have anything within SEO that will do this (yet). In the mean time, you could use Craft's built in Find and Replace (in the Utilities section) to change all the title suffixes.

**Comment by rinusvandam** [comment]
Thanks, that did work.

Just one thing: find and replace added two spaces after the SEO field entry. That ended up as an empty <title> </title> with two spaces inside. Deleting the two spaces after the text made the correct title appear.

**Comment by Tam** [comment]
This is resolved with our upcoming dynamic meta feature. It's currently in beta, so if you get a chance we'd really appreciate some testers! See [[Beta] Dynamic Meta](https://github.com/ethercreative/seo/issues/167) for more info.
