### ISSUE TITLE
(Craft 2) SEO Properties not working on Categories

### ISSUE THREAD

**Issue by JMKelley** [ethercreative/seo#80]
### Description
SEO Properties are not set when entered for an SEO field type on a category page.

### Steps to reproduce

1. Add SEO field to a Category
2. Add Text to SEO Title
3. Title Does not Appear.

### Additional info

- Craft version: 2.6.3
- SEO version: Latest
- PHP version:
- Database driver & version:
- Other Plugins:

**Comment by Tam** [comment]
Fixed in v3.2.3
