### ISSUE TITLE
Only sections enabled for primary site is listed

### ISSUE THREAD

**Issue by larsboldt** [ethercreative/seo#83]
### Description
All sections not enabled for our primary site is not listed in the sitemap list.

### Steps to reproduce

1. Disable section for primary site
2. Go to sitemap configuration

### Additional info

- Craft version: 3.0.1
- SEO version: 3.2.3
- PHP version: 7.2
- Database driver & version: mysql 5.7

**Comment by larsboldt** [comment]
Digging more in the code the problem seems to be the _filterOutNoUrls function. Since its based on currentSite->id and there is no option to switch between sites, only primary site listings will show.

Adding a site switcher in the header might remedy this?

**Comment by Tam** [comment]
v3.2.4 now shows all sections regardless of site. I've added an issue to improve site handling on this section at some point!
