### ISSUE TITLE
Installation Issues

### ISSUE THREAD

**Issue by kaspar-allenbach** [ethercreative/seo#85]
It' doesn't work. Am I missing something?

- Installed the plugin
- Added SEO Field to entry
- Added some text
- Added `{% hook "seo" %}` into `<head>`

Now the seo tags are rendering but without any content. Do I need to do something else

**Comment by Tam** [comment]
@kaspar-allenbach What version of the plugin and craft are you using?

**Comment by tomastech** [comment]
@kaspar-allenbach The hook expects field handle (that's attached to the entry) to be named "seo".

See the default meta template:
https://github.com/ethercreative/seo/blob/v3/src/templates/_seo/meta.twig

**Comment by kaspar-allenbach** [comment]
@tomastech Oh, okay, I guess that's the problem. I will try it out.

- I'm on Craft 3.0.1
- SEO Plugin 3.2.3
- PHP 7.1.12 (local MAMP environment)

**Comment by jayhlee** [comment]
Had the same issue as @tomastech . Would be great if the field handle can be any name and the hook would recognize whatever field handle you set the SEO field type to.

**Comment by missmatsuko** [comment]
https://github.com/ethercreative/seo/blob/v3/src/templates/_seo/meta.twig
```
{# Tip: You can pass the handle of your SEO field - getSeoField('mySeoFieldHandle') #}
	{% set seo = getSeoField() %}
```

If passing the handle of the SEO field into getSeoField() works, would it be a small change to the default template to make it work for fields with any handle?

**Comment by TBSH01** [comment]
New to Craft. I have the plugin installed and it appears within Craft admin (v2.8.0.1). 

Trying to use this plugin, but don't understand where I should add/edit the Fieldtype Usage & Custom SEO Object craft.seo.custom() code.
