### ISSUE TITLE
SEO Title - prefix instead of suffix

### ISSUE THREAD

**Issue by CreateSean** [ethercreative/seo#86]
### Description

I would like to be able to set the site title as a prefix to the page title rather than as a suffix. I have a client that insists on the site title being first.

will this be possible?

### Steps to reproduce

1.
2.

### Additional info

- Craft version: 3.0.1
- SEO version: 3.2.3
- PHP version:
- Database driver & version:
- Other Plugins:

**Comment by Tam** [comment]
Added in v3.2.4

**Comment by wihodges** [comment]
On version '3.3.0' of plugin – I don't see anywhere to change this to prefix.
