### ISSUE TITLE
[FR] Canonical URL Support

### ISSUE THREAD

**Issue by alexjcollins** [ethercreative/seo#88]
### Description

Add canonical URL field to the field type and update the default template to include support

**Comment by eastriverstudio** [comment]
Is there still a plan to implement a feature for this? I recently noticed how the default template creates the canonical url using getAbsoluteUrl that if any referral links containing query string parameters (for example we noticed Facebook started adding query string to shared urls) these get set as the canonical url which is not ideal. So I'd be interested in this feature to have some control over this in the CP and avoid this problem when visitors are coming from referral links with extra parameters.

**Comment by alexjcollins** [comment]
Hi @gTaylorRokk yeah, definitely still on the roadmap. We're a behind on a bunch of updates we want to push asap, so have planned to give some focus to the plugin in January. Hopefully we'll have som e good news for you soon.
Watch this space 👀

**Comment by eastriverstudio** [comment]
@alexjcollins thanks for confirming that. I'll look forward to the future updates and thanks for the work on this excellent plugin.
