### ISSUE TITLE
Sitemap doesn't seem to be valid XML

### ISSUE THREAD

**Issue by darylknight** [ethercreative/seo#91]
### Description
I just enabled Sitemaps on a new staging site, enabled some sections and checked it out, seems like it's not formatted how I'd expect to see an XML file. Is this correct?

### Steps to reproduce

1. Visit http://jumpgiants.codeknight.co.uk/sitemap.xml

### Additional info

- Craft version: 3.0.3.1
- SEO version: 3.2.4
- PHP version: 7.1.16

**Comment by EricParks** [comment]
I'm seeing the same issue on a site I'm developing.

**Comment by Tam** [comment]
I've run your sitemap through a couple of different validators @darylknight, and all are confirming that it is valid. Could you or @EricParks give me an example of what is wrong?

**Comment by EricParks** [comment]
I get an "incorrect http header content-type" error when I run a validator on both my local instance as well as with the link @darylknight provided.

**Comment by alexjcollins** [comment]
@EricParks what validator are you using?

**Comment by EricParks** [comment]
https://www.xml-sitemaps.com/validate-xml-sitemap.html

However, I just tried it with a few other validators, and those come back valid. So it could just be an issue with that one validator.
