### ISSUE TITLE
Undefined index: social when editing entries after upgrade to Craft 3

### ISSUE THREAD

**Issue by nickcobley** [ethercreative/seo#92]
After upgraded from Craft 2.6.3015 and  2.1.3 of the SEO plugin, if I edit any entries I get the error:

`
Undefined index: social
`

In short I tracked this down to the data contained within the SEO field on the source database, which was structured something like this

`
{"title":"Test Title | Site Name","description":"","keyword":"","score":""}
`

Resaving the entry prior to the upgrade created the newer fields of:

`{"title":"Test Title | Site Name","description":"","keywords":"[]","score":"","social":{"twitter":{"image":"","title":"","description":""},"facebook":{"image":"","title":"","description":""}}}`

This for me once I then do the database migration again fixes the problem. There was a suggestion that resaving the section would force all the entries to be resaved again, this didn't work for me however so I just manually resaved every entry. 

The actual error

```
1. in /var/www/vhosts/***/vendor/ether/seo/src/fields/SeoField.php at line 92
8384858687888990919293949596979899100101                    	{
        if (empty($value))
            return self::$defaultValue;
 
        if (!is_array($value))
            $value = Json::decode($value);
 
        // Social
 
        $social = array_merge(self::$defaultValue['social'], $value['social']);
        foreach ($social as $k => $s)
        {
            if ($s['image'] !== '')
            {
                if (
                    is_object($s['image'])
                    && get_class($s['image']) === 'craft\elements\Asset'
                ) continue;
```
 
                

### Additional info

- Craft version: 3.04
- SEO version: 3.2.4 
- PHP version: 7.0.29

**Comment by Tam** [comment]
There's currently no support for upgrading from Craft 2 to 3 I'm afraid, it's on our todo list!

**Comment by nickcobley** [comment]
Regardless of if there is support for it. With that tweak and remapping the field I now have 1000+ entries migrated from Craft 2 that now work just fine, I'm not using every area of the plugin but for my simple needs it's working.
