### ISSUE TITLE
Sitemap error if seo field isn't present

### ISSUE THREAD

**Issue by webrgp** [ethercreative/seo#96]
### Description

Getting a "Unknown Property – yii\base\UnknownPropertyException. Getting unknown property: craft\elements\Entry::" error when trying to access the sitemap without having the seo field present.

### Steps to reproduce

1. Have the sitemap set, and access the sitemap link, like "/sitemap_sections_4_0.xml"
2. Make sure that section doesn't have a seo field set.

### Proposed solution

Wrap `src/services/SitemapService.php` around line 295 with a if statement:

```php
if ( $seoFieldHandle !== null) {
	$seoField = $item->$seoFieldHandle;
	if ($robots = $seoField['advanced']['robots'])
		if (in_array('noindex', $robots))
			continue;
}
```

**Comment by justinmacleod** [comment]
@Tam I believe this issue might be reoccurring. I was able to reproduce the issue under version 3.4.4 when I had a section with multiple entry types. In my use case, one of these entry types didn't have the SEO field added. I received the following error:

`yii\base\ErrorException: Trying to get property 'advanced' of non-object in /var/www/emeraldhealth.ca/vendor/ether/seo/src/services/SitemapService.php:305`

Once I added the SEO field, the issue went away and the sitemap was successfully displayed.

**Comment by aaronwaldon** [comment]
I too would love to see this patched. Sometimes it's nice to have the SEO fields in certain entry types, but not others in the same section. Currently that scenario breaks the entire site map for the section. 

I think another alternative to this fix would be to use `property_exists` instead of `is_object`:

```
if (!property_exists($seoField, 'advanced')) {
	continue;
}
```
