### ISSUE TITLE
robots.txt can not be directly called without login as admin

### ISSUE THREAD

**Issue by ghost** [ethercreative/seo#97]
https://github.com/ethercreative/seo/blob/d36af2ef7a1cb4124a0e74e77a5052c817cf7825/src/controllers/SeoController.php#L16

Reproduce: call for /robots.txt when you are not logged in as admin.
Solution: make a new controller for robots with property: `protected $allowAnonymous = true;`

**Comment by RyanHavoc** [comment]
Should you be able to access a generated robots.txt file by simple visiting `yourdomain.com/robots.txt` then?

As I get a 404 error...
