### ISSUE TITLE
Adding Custom SEO Properties

### ISSUE THREAD

**Issue by JMKelley** [ethercreative/seo#98]
### Description
I have a client who's importing around 8000 entries to their Craft site. They have a boilerplate meta description they want to use with some twig elements such as {{ entries.count }} etc.

I see there is a Custom SEO Object that I can place on pages that need custom properties set. How would I go about using this? I've tried a few tags to no avail.

**Comment by Tam** [comment]
You can override the an SEO field from a template using a [Custom SEO Object](https://github.com/ethercreative/seo#custom-seo-object).
